var motivationTextEn = ["Dance, sing, whistle whenever the mood strikes, because the day will come when all you hear is the silence of your grave", "Happiness is all a matter of perspective", "You can either live out your dreams or your fears", "Fear’s in your head<br>But so is courage", "You’re never going to be as young as you are today!", "You’re a winner!", "Believe in yourself<br>", "Today is a gift and the only day which you can change", "Never give up and stick with it until you succeed!", "Be brave and take risks because that’s only way you can achieve greatness", "Humour is the father and laughter the mother of a happy soul", "Be thankful for everything, including your problems, because this is the fertiliser that will help you to grow!", "Love is not just the foundation of all things; it is also the pinnacle of all things", "If you want to experience a miracle in your life, get rid of your fear and doubts", "The direction of your thinking and your action is always forward, into the future. That’s why God gave you eyes that face forward", "A true friend will always carry you from one height to another. You can choose your friends", "Believe in yourself. Believe that the divine energy is in you and on your side at all times", "Always be yourself in the here and now. Compliment yourself and others. Turn yourself and those around you into giants", "The key to happiness lies inside you", "Believing in your purpose with all your heart<br>is the secret of the gods", "You are the most important person in your life, so love yourself and respect yourself", "Happiness doesn’t depend on who you are or what you have. It depends on how you think", "Pain and stress are the first sprouts on the way to success", "You are unique", "If you embody love, then fear itself will be afraid and flee", "Your thoughts are food for your soul.", "You alone are the director of your life", "Clean your life by cleaning up your thoughts", "What’s important is not where you’re at today or where you’ve come from. What’s important is where you’d like to go", "noNever stop smiling<br><img src='img/lachen_musst_selber.jpg' class='img-circle'><br>even when you’re really sad, because you never know who might just fall in love with your smile<br>", "noWhen others think you’re finished<br><img src='img/weiter1.jpg' class='img-circle'><br>is where you’re actually just getting started", "noIf God wants to give you a special gift, he’ll wrap it in a problem<br><img src='img/problem_ist_ein_geschenk.jpg'>", "Believe in yourself. If you don’t, who will?", "noYou’re a diamond<br><img src='img/du_bist_ein_diamant1.jpg' class='img-circle'><br>in the rough and also the sharpening stone", "noMiracles happen <br><img src='img/glueck3.jpg' class='img-circle'>when you purify your mind of all fears and doubts", "Let go and become richer<br>", "noHave the courage to master the challenges in your life<br><img src='img/hindernis.jpg' class='img-circle'>", "The more love for yourself that you show, the more certain people and positive situations you’ll attract", "Set yourself goals, divide them into steps, and then walk the walk, step-by-step", "Whether you win or lose depends on what’s going on between your ears.", "The world belongs to those who want to conquer it with love and good spirits", "Enjoy the moment because the moment is your life", "You don’t need to be better than everyone else. You just need to be better than you ever imagined you could be", "When the future’s facing you, give it the chance to be experienced! When uncertainty’s facing you, give it the chance to become certainty! When reason’s blocking your path, give yourself the opportunity to decide from your gut. When love’s standing there, give it every chance in the world!", "noYou don’t need to do everything right in life. There won’t be any grades on your gravestone<img src='img/lu1.jpg' class='img-circle'>", "noLoving yourself lets the butterflies fly<br><img src='img/du_bist_ein_schmetterling.jpg'>", "Just be yourself", "Every hour, every minute of your life is a gift. Don’t postpone anything that makes you happy. Because you never know how much time you’ll have left...", "We need to understand that earth is a school where we have certain things to learn, for example, patience, perspective, spiritual and creative powers, and especially love, both love for yourself and for others. Love is the most important and best homework you’ll ever get in the school of life", "Do you want to be happy? Then don’t live in the past, don’t live in the future, just live in the moment and appreciate just how unique it is", "noGod gave you a face, but you’ve got to do the laughing yourself<br><img src='img/lachen_musst_selber.jpg' class='img-circle'><br>", "noMiracles begin<br><img src='img/glueck3.jpg' class='img-circle'> when we devote more energy to our dreams than to our fears", "Give every day the chance to be the best day of your life", "The hardest times often lead to the best moments in your life. Keep the faith. Everything will be worth it in the end<br>", "Be brave enough to start. It’s never too late to do what you could have done<br>", "You can’t decide everything that’s going to happen in life, but you can decide how you’re going to handle it. Don’t let your past define your present, instead let it give you advice for the future", "Everything that you are, everything that you want, everything that you should be, comes from inside", "You are unique. Believe in yourself now and for ever.", "Whatever you think, you’ll achieve. Whatever you feel, you’ll attract. Whatever you imagine, you will receive<br>&#x1f496;", "No matter what you do, they’ll think of you the way they want to, so do what you want to do and be the person you really are, because that’s how you’ll feel good with yourself", "Take your life into your own hands, or else others will do it for you", "Everything you need to be successful is already inside you", "Be brave enough to change<br>", "Be grateful for what you have while you work for what you want", "Walk your path and believe in yourself, no matter what others say", "It’s your life. Believe in yourself<br>", "noYour motivation machine<br><img src='img/motivationsmaschine.jpg' class='img-circle'>"];

var motivationTextEs = ["Baila, canta y silba cuando siempre tengas ganas, porque llegará el momento en el que solo escucharas el silencio de tu tumba", "La felicidad se produce con la forma de pensar", "Puedes vivir tus visiones o tus miedos", "El miedo empieza en la cabeza, por supuesto el coraje tambien", "Tan joven como hoy no volveras a serlo en toda tu vida!", "Tu eres un ganador! Creé en tí!", "El hoy es un regalo y el único día en el que puedes cambiar algo", "nunca … nunca … jamas te des por vencido y ten el aguante para tener éxito", "Ten el valor para riesgos, porque solo através de este valor podras obtener la verdadera grandeza", "El humor es el padre , la risa  la madre de personas felices", "Se agradecido por todo, porque eso es el abono para poder crecer", "El amor no es solo el fundamento de todas las cosas, es mucho mas, es también la cima de todas las cosas", "Si quieres atraer un milagro a tu vida, despide el miedo y la duda de tu mente", "Mantén la dirección de tus pensamientos y acciones siempre para adelante en el futuro, pues tu creador te dió los ojos hacia adelante", "Un verdadero amigo te inspira de pico a pico, tu puedes elegir a tus amigos", "Cree en ti, cree en la energia divina que siempre está contingo y siempre está para ti", "Se siempre tu mismo en el ahora y aqui, piropéate  y piropéa a los demas, hazte gigante y haz a los demas gigantes", "La llave para tu felicidad está en ti mismo", "Cree de corazon en tu meta<br>eso es el misterio de dios", "Tú eres la persona más importante en tu vida, por eso ámate y respétate a ti mismo", "La suerte no depende de quien eres o de lo que tienes, solo depende de lo que piensas", "El dolor y el efuerzo son los escalones hacia éxito", "Tú eres único", "Si vives el amor, el miedo tiene miedo y huye", "Tus pensamientos son el alimento de tu alma", "Solo tú eres el director de tu vida", "Purifica tu vida  através de la purificación de tus pensamientos", "No es importante donde estas ahora o de dónde vienes, lo importante es adonde quieres ir", "noNunca dejes de sonreird<br><img src='img/lachen_musst_selber.jpg' class='img-circle'><br>ni siquiera cuando estés muy triste, porque nunca se sabe quién se podría enamorar de tu sonrisa<br>", "noCuando los demas piensen que te vas a dar por vencido<br><img src='img/weiter1.jpg' class='img-circle'><br>entonzes más que nunca sique con lo tuyo", "Cuando Dios te quiere hacer un regalo especial, lo empaqueta en un problema", "Cree en ti, porque si no lo haces tú, quién va creer en ti?", "noTú eres el diamante<br><img src='img/du_bist_ein_diamant1.jpg' class='img-circle'><br>y también la piedra de afilar", "Milagros ocurren si purificas tu mente de todas las angustias y dudas", "Suelta y de este modo enriqueze", "noTen el valor para superar los obstáculos de tú vida<br><img src='img/hindernis.jpg' class='img-circle'>", "Cuanto más amor propio rezumas, más personas y situaciones positivas atraeras", "Ponte metas, repartelas en etapas y anda paso a paso", "Es entre las orejas donde se gana o se pierde", "El mundo es de aquellos quienes salen a conquistar, armados con amor y buen humor", "Disfruta del momento, porque el momento es tu vida", "No tienes que ser mejor que todos los demás, solo tienes que ser mejor de lo que tu jamas hubieras pensado poder ser", "Si el futuro está delante de ti, dale la oportunidad de ser vivido. Si la incertidumbre está delante de ti, dale la oportunidad de convertirse en certeza. Si la razón está delante de ti, dale la oportunidad de que pueda decidir por intuición. Si el amor está delante de ti, dale todas las oportunidades del mundo<br>", "noNo hay que hacer todo bien en la vida, el la lápida no ponen notas<br><img src='img/lu1.jpg' class='img-circle'>", "noTú eres una mariposa, porque el amor propio tambien deja volar mariposas<br><img src='img/du_bist_ein_schmetterling.jpg'>", "noCachondo es …. zılǝɟ ɹǝs ʎ ɐqıɹɹɐ sɐʇɐd opunɯ lǝ opuɐnɔ uǝ zǝʌ ǝp ɹǝuod<br><img src='img/umdrehen.jpg' class='img-circle'>", "Se soló tu mismo", "Cada hora, cada minuto de tú vida es un regalo. No aplazes nada de lo que dé placer, porque nunca se sabe cuanto tiempo te queda …", "Tenemos que entender, que la tierra es una escuela en la cual tenemos que aprender ciertas cosas. Por ejemplo paciencia, tolerancia, el desarollo de capacidades mentales y creativas y sobre todo amor, amor de sí mismo y amor a los demás. Amor es en todas las clases de la escuala de la vida la asignatura principal y por lo tanto la tarea mas bonita e importante", "noQuieres ser feliz?<br><img src='img/glueck3.jpg' class='img-circle'><br>Pues entonces no vivas en el pasado, no vivas en el future, sino vive ahora en este momento y goza de este momento único<br>", "noDios te dió el rostro, pero reir tienes que reirte tu mismo<br><img src='img/lachen_musst_selber.jpg' class='img-circle'>", "noMilagros empiezan a cumplirse cuando damos <br><img src='img/glueck3.jpg' class='img-circle'>más energia a nuestros sueños que a nuetros miedos", "Dale a cada día la oportunidad de ser el más bonito de tú vida", "Los momentos más dificiles conducen a menudo a los momentos más maravillosos de tú vida", "La valentía está al principio. Nunca es tarde para llegar a ser lo que uno hubiera podido ser", "No puedes elegir lo que en la vida va a suceder, pero puedes elegir cómo manejar la situación. No dejes de que el pasado mande en el presente y deja ser al pasado un buen aconsejador del futuro", "Todo lo que eres, todo lo que quieres, todo lo que debes, sale de tí mismo", "Tú eres único. Cree en tí. Ahora y para siempre", "Lo que piensas, vas a crear. Lo que sientes, vas a atraer. Lo que te imaginas, lo vas a recibir<br>&#x1f496;", "Da lo mismo lo que hagas, todo el mundo va a pensar lo que quiera de tí, por eso haz luego lo que de corazón quieras y sé la persona que realmente eres, ya que entonces vas a sentirte bien contigo mismo<br>&#x1f497;", "Toma tú vida en tus propias manos, de lo contrario otros lo harán por tí", "Todo lo que necesitas para tener éxito ya lo tienes dentro de tí", "Se una y otra vez valiente para cambiarte", "Se agradecido de lo que tienes mientras que trabajas por lo que pretendes", "Sigue tú camino y cree en ti mismo, no importa lo que digan los demás", "Es TU vida, cree en ti<br>", "noSu motivación máquina<br><img src='img/motivationsmaschine.jpg' class='img-circle'>"];

var motivationTextTest = [
    "noDzikie wilki i bezpretensjonalne kobiety mają wiele wspólnego:<img src='img/wolf.jpg' class='img-circle'>precyzję instynktownej wrażliwości, upodobanie do wszystkiego, co zabawne, i niemal niezachwianą lojalność<br><br>Clarissa Pinkola Estes",
"To takie cenne i piękne, że istniejesz."
];

var motivationTextPL = [
"Nie pozwól, aby odebrano Ci blask, tylko dlatego, że mógłbyś oślepiać innych!",    
"noDzikie wilki i bezpretensjonalne kobiety mają wiele wspólnego:<img src='img/wolf.jpg' class='img-circle'>precyzję instynktownej wrażliwości, upodobanie do wszystkiego, co zabawne, i niemal niezachwianą lojalność<br><br>Clarissa Pinkola Estes",
"To takie cenne i piękne, że istniejesz.",
"Twoim prawdziwym bogactwem są Twoje myśli.",
"Dąż do bycia pierwszym: jako pierwszy skinij głową, uśmiechnij się, pochwal i przebacz.",
"Jesteś sobą, gdy nie kwestionujesz już swoich działań.",
"Nie czekaj, aż ludzie uśmiechną się do Ciebie, pokaż im, jak to się robi!",
"Ucz się na błędach, aż przestaniesz je popełniać.",
"Wdech<br>Wydech<br>Szczęście.",
"Masz zdolność motywowania się do działania. Po prostu to zrób!",
"Każda, nawet najdłuższa podróż, zaczyna się od pierwszego kroku.",
"Złamane serce nie jest tego warte. Kiedy półbogowie odchodzą, przychodzą bogowie.",
"Czy wiesz, że motyl nie może zobaczyć swoich skrzydeł? Nie wie, jak piękne są, ale wszyscy inni to widzą. Podobnie jest z ludźmi.",
"Miej słońce w sercu, bez względu na burze czy śnieg. Słońce rozświetli Ci nawet najciemniejszy dzień.",
"Bez względu na to, co się dzieje, wierz w siebie! Bez względu na wszystko, bądź wierny sobie!",
"Sekretem bogów jest ciągłe wierzenie w siebie.",
"Szczęście tkwi w działaniu.",
"Wytrwałość to ukryta siła sukcesu. Bądź niezłomny.",
"Jestem wdzięczny za kamienie, które stanęły na mojej drodze. Bez nich nie odkryłbym swojej siły.",
"Nigdy nie zadowolisz wszystkich swoimi działaniami. Nawet jeśli będziesz chodzić po wodzie, ktoś powie, że nie umiesz pływać.",
"Nie marnuj energii na negatywy. Skup się na pozytywnym celu i tym, co chcesz osiągnąć.",
"Pokochaj siebie takim, jakim jesteś, a nie takim, jakim chcieliby Cię widzieć inni.",
"Jesteś cudowny.",
"Przeznaczenie to to, co z niego zrobisz.",
"Bądź szczęśliwy tu i teraz.",
"Przestań się porównywać, uśmiechnij się do lustra.",
"Pamiętaj o swoich marzeniach, one za Tobą tęsknią.",
"Jeśli dmuchawiec potrafi przebić się przez asfalt, Ty również znajdziesz swoją drogę!",
"Postanowiłem nie czekać na lepsze czasy. Najlepszy czas jest teraz.",
"Bez względu na sytuację, w jakiej się znajdujesz, wierz w najważniejszą osobę – siebie!",
"Ciesz się życiem. Utracony czas nigdy nie wróci. Żyj swoimi marzeniami i nie poddawaj się w ich realizacji.",
"Życie to przygoda: żyj, czuj, kochaj, śmiej się, płacz, graj, wygrywaj, przegrywaj, potykaj się… ale zawsze wstań i idź swoją drogą.",
"Nigdy nie wstydź się podejmować działań, które mogą zmienić Twoje życie. To może być Twoje szczęście.",
"Tańcz, śpiewaj i gwizdaj, kiedy tylko masz na to ochotę, bo kiedyś usłyszysz tylko ciszę swojego grobu.",
"Bądź zawsze wierny sobie, ze wszystkimi swoimi pragnieniami i marzeniami. Nie udawaj i idź swoją drogą. Przebacz sobie swoje słabości z miłością i bądź dzięki temu silny.",
"Ten moment jest wyjątkowy i nigdy nie wróci. Nie czekaj na idealny moment. Spraw, by był idealny dla Ciebie.",
"Dziś jest pierwszy dzień reszty Twojego życia.",
"Z miłością przebaczam sobie swoje słabości i dzięki temu jestem silny.",
"Rozpoznaj, że dzisiejszy dzień to Twoja szansa.",
"Zawsze jesteś swoim własnym nauczycielem.",
"Perfekcja jest nudna i powstrzymuje Cię przed ukończeniem swoich działań.",
"Nie ma nic większego niż wiara w siebie!",
"Szczęście wynika z Twojego sposobu myślenia.",
"Bóg słucha myśli.",
"Możesz żyć swoimi wizjami lub swoimi lękami.",
"Strach rodzi się w głowie. Odwaga również.",
"Jesteś zwycięzcą!",
"Uwierz w siebie!",
"Dziś jest prezent i jedyny dzień, w którym możesz coś zmienić.",
"Nigdy się nie poddawaj. Miej wytrwałość, by osiągnąć sukces!",
"Miej odwagę podejmować ryzyko, bo tylko dzięki temu możesz zyskać prawdziwą wielkość.",
"Humor jest ojcem, a śmiech matką szczęśliwego człowieka.",
"Bądź wdzięczny za wszystko, nawet za swoje problemy. To nawóz dla Twojego wzrostu.",
"Miłość jest nie tylko fundamentem wszystkiego, jest również szczytem wszystkiego.",
"Chcesz przyciągnąć cud do swojego życia? Uwolnij swoje myśli od strachu i zwątpienia.",
"Kierunek Twojego myślenia i działania zawsze prowadź naprzód w przyszłość.",
"Prawdziwy przyjaciel zawsze motywuje Cię, byś wspinał się od jednego szczytu do drugiego. Możesz sam wybrać swoich przyjaciół.",
"Wierz w siebie i w boską energię, która zawsze jest w Tobie i dla Ciebie.",
"Zawsze bądź sobą w tu i teraz.",
"Klucz do Twojego szczęścia znajduje się w Tobie.",
"Wiara w swoje cele to sekret bogów.",
"Jesteś najważniejszą osobą w swoim życiu, więc kochaj i szanuj siebie.",
"Szczęście nie zależy od tego, kim jesteś, czy co masz, ale od tego, co myślisz.",
"Ból i wysiłek to szczeble drabiny prowadzącej do sukcesu.",
"Jesteś wyjątkowy.",
"Najwiekszym bledem, ktorego nie mozesz popelnic, jest strach przed popelnieniem bledu."
];


var motivationTextIt = [
"Non trattenere mai i complimenti. Non c'è motivo per farlo",
"Ora ti assumi personalmente la responsabilità dei tuoi pensieri e della tua vita. Sei potente e dinamico",
"Sii gentile con te stesso",
"Lupi selvaggi<img src='img/wolf.jpg' class='img-circle'>e donne autentiche hanno molto in comune: la precisione del loro istinto sensibile, una predilezione per tutto ciò che è giocoso e una lealtà incrollabile<br><br>Clarissa Pinkola Estes",
"Non lasciare che la tua luce venga spenta solo perché potrebbe abbagliare gli altri!",   
"È così prezioso e bello che tu esista",    
"La tua vera ricchezza sono i tuoi pensieri.",
"<img src='img/erster.png'>Cerca di essere il primo: il primo a fare un cenno, il primo a sorridere, il primo a fare un complimento e il primo a perdonare.",
"Sei te stesso quando smetti di mettere in discussione le tue azioni",
"Non aspettare che le persone ti sorridano, <img src='img/zeigeesihnen.jpg'>mostra loro come si fa!",
"Impara dagli errori fino a non commetterli più.<img src='img/lernen.jpg' class='img-circle'>",
"Inspira<br>Espira<br>Sii felice<img src='img/gluecklich1.jpg' class='img-circle'>",
"noHai la capacità di motivarti all'azione.<br><img src='img/doit.png' class='img-circle'> Fallo e basta!",
"Ogni viaggio, anche il più lungo, inizia con il primo passo<img src='img/doit.png' class='img-circle'>",
"Non vale la pena soffrire per amore. <img src='img/neuanfang.jpg'> Quando se ne vanno i semidei, arrivano gli dèi",
"no<img src='img/butterfly.jpg' class='img-circle'>Sapevi che è impossibile per una farfalla vedere le proprie ali?<br> E sapevi anche che le sue ali sono considerate una delle meraviglie più belle della natura?<br>Non può vedere quanto siano belle, ma tutti gli altri possono.<br>Lo stesso vale per noi esseri umani<img src='img/butterfly1.jpg'>",
"no<img src='img/sun1.jpg' class='img-circle'>Abbi il sole nel cuore, indipendentemente dal fatto che ci siano tempeste o neve, che il cielo sia pieno di nuvole o la terra piena di litigi - abbi il sole nel cuore e, qualunque cosa accada, illuminerà i tuoi giorni più bui<img src='img/sun.jpg' class='img-circle'>",
"Qualunque cosa accada. Credi in te stesso!<br>Qualunque cosa accada. Rimani fedele a te stesso!<br>Qualunque cosa accada. Amati!<br>",
"E credere sempre in te stesso è il segreto degli dèi.",
"La felicità si trova anche nell'agire e nel fare.",
"La perseveranza è la forza segreta del successo. Sii incrollabile.",
"noSono grato per le pietre che mi sono state messe sul cammino.<img src='img/steine.jpg' class='img-circle'>Senza di esse non sarei inciampato sulle mie forze.",
"<b>Non puoi entusiasmare tutti con ciò che fai.</b><br>Anche se potessi camminare sull'acqua, ci sarà sempre qualcuno che ti chiederà perché non sai nuotare.",
"noNon spendere così tanta energia sulle cose negative.<img src='img/bogen1.jpg' class='img-circle'>Concentrati sul tuo obiettivo positivo e su ciò che vuoi raggiungere.<img src='img/bogen2.jpg' class='img-circle'>",
"Inizia ad amarti per come sei e non per come gli altri vorrebbero vederti.",
"Sei MERAVIGLIOSO",
"Il destino è sempre ciò che ne fai",
"Sii semplicemente felice nel presente<img src='img/t161.jpg' class='img-circle'>",
"Smetti di confrontarti, sorridi allo specchio",
"Pensa ai tuoi sogni, sentono la tua mancanza.",
"Sii semplicemente felice nel presente",
"no<img src='img/loewenzahn.jpg' class='img-circle'><br>Se un dente di leone riesce a passare attraverso l'asfalto, allora sicuramente anche tu troverai un modo!",
"noHo deciso di non aspettare più tempi migliori.<br>I migliori tempi sono ora.<br>Rendo gli anni restanti della mia vita i più felici.<img src='img/jetzt.jpg' class='img-circle'><br>Perché la vita è mia ed è semplicemente troppo breve per aspettare ancora.",
"Qualunque sia la situazione in cui ti trovi. Credi nella persona più importante = TE STESSO",
"Goditi la tua vita. Il tempo perduto non torna mai. Vivi nel tuo sogno e non smettere mai di realizzarlo",
"La vita è come un'avventura, vivi, senti, ama, ridi, piangi, gioca, vinci, perdi, inciampa... ma rialzati sempre e continua per la tua strada",
"Non essere mai troppo orgoglioso per intraprendere qualcosa che potrebbe cambiare la tua vita.<br>Potrebbe essere la tua felicità.",
"Balla, canta e fischia ogni volta che ne hai voglia<br>perché un giorno sentirai solo il silenzio della tua tomba",
"Rimani sempre fedele a te stesso, con tutti i tuoi desideri e sogni. Non fingere e segui la tua strada. Perdona le tue debolezze con amore e diventa forte attraverso di esse.",
"Questo momento è unico e non tornerà mai. Non aspettare il momento perfetto. Rendilo perfetto per te.",
"Oggi è il primo giorno del resto della tua vita.",
"Con amore perdono le mie debolezze e divento forte attraverso di esse",
"Riconosci che la tua occasione si trova nella giornata di oggi",
"Sei sempre il tuo insegnante",
"La perfezione è terribilmente noiosa e ti impedisce di finire il tuo lavoro",
"Non c'è niente di più grande che credere in te stesso!",
"La felicità nasce dal tuo modo di pensare",
"Dio ascolta i pensieri",
"Puoi vivere le tue VISIONI o le tue paure",
"La paura inizia nella mente<br>Ma anche il coraggio", 
"noLa tua macchina della motivazione<img src='img/motivationsmaschine.jpg' class='img-circle'>",
"Così giovane come oggi non lo sarai mai più<br>nella tua vita!",
"Sei un vincitore!", "Credi in te stesso",
"Oggi è un regalo<br> ed è l'unico giorno<br>in cui puoi fare la differenza",
"Non arrenderti<br>mai<br>mai<br>e abbi la perseveranza per raggiungere il successo!",
"Abbi il coraggio di correre rischi<br>perché solo attraverso questo coraggio<br>puoi ottenere una vera grandezza",
"L'umorismo è il padre &#9786;<br>il sorriso la madre<br>di una persona felice<br><img src='img/humor.jpg' class='img-circle'>",
"Sii grato per tutto<br>Anche per i tuoi problemi<br>perché sono il fertilizzante<br>per la tua crescita!",
"L'amore non è solo il fondamento di tutte le cose <br>&#9825;è molto di più<br>&#9825;<br>è anche la cima di tutte le cose",
"Se vuoi attirare un miracolo nella tua vita<br><br>lascia andare la paura e il dubbio<br>dai tuoi pensieri",
"La direzione dei tuoi pensieri e delle tue azioni<br>mantienila sempre verso il futuro<br><br>perché il tuo Creatore ti ha dato gli occhi davanti",
"Un vero amico ti dà sempre ali<br>per arrivare da una cima all'altra.<br>Puoi scegliere i tuoi amici",
"Credi in te stesso<br><br>Credi che l'energia divina sia sempre in te<br>e per te",
"Sii sempre te stesso<br>nell'Adesso e Qui<br>fai complimenti a te stesso e agli altri<br>rendi te stesso e gli altri grandi",
"La chiave &#9825;<br>della tua felicità<br>è dentro di te",
"Credere nel tuo obiettivo con il cuore<br> è il segreto degli dèi",
"Tu sei la persona più importante della tua vita<br>quindi amati &#9825;<br>e rispettati", 
"no<img src='img/glueck3.jpg' class='img-circle'><br>La felicità non dipende<br>da chi sei o da cosa possiedi<br>dipende solo<br>da ciò che pensi",
"Dolore e fatica<br>sono i gradini della scala<br>verso il successo",
"Sei<br>&#9825;<br>unico", 
"Se vivi l'amore<br>&#x1f496;<br>allora la paura ha paura e fugge",
"I tuoi pensieri<br>sono il nutrimento<br>per la tua anima<br>",
"Solo tu<br>sei il direttore<br>della tua vita&nbsp;&#9835;",
"Purifica la tua vita<br>purificando<br>i tuoi pensieri",
"Purifica la tua vita<br>purificando<br>i tuoi pensieri",
"Non importa dove sei ora o da dove vieni<br>l'importante è dove vuoi andare",
"noNon smettere mai di sorridere<br><img src='img/lachen_musst_selber.jpg' class='img-circle'><br>neanche quando sei molto triste<br>perché non sai chi potrebbe innamorarsi del tuo sorriso<br>",
"noQuando gli altri pensano che tu sia alla fine<br><img src='img/weiter1.jpg' class='img-circle'><br>inizia davvero",
"noQuando Dio vuole farti un dono speciale<br>lo avvolge in un problema<br><img src='img/problem_ist_ein_geschenk.jpg'>",
"Credi in te stesso<br>perché se non lo fai tu<br>chi dovrebbe farlo?",
"noSei un diamante<br><img src='img/du_bist_ein_diamant1.jpg' class='img-circle'><br>e anche la mola per levigarlo",
"I miracoli accadono<br><br>quando purifichi i tuoi pensieri<br>da tutte le paure e i dubbi",
"Lascia andare<br>e diventa più ricco<br>in questo modo",
"noAbbi il coraggio<br>di superare gli ostacoli della tua vita<br><img src='img/hindernis.jpg' class='img-circle'>",
"Più amore per te stesso irradi<br>più persone ben disposte e situazioni positive<br>attrarrai<br>",
"Fissati degli obiettivi<br>dividili in tappe<br>e procedi passo dopo passo",
"Tra le orecchie si vince o si perde",
"Il mondo appartiene a coloro che si lanciano alla sua conquista<br>armati di amore e buon umore",
"Goditi l'attimo<br>perché l'attimo<br>è la tua vita",
"Non devi essere migliore di tutti gli altri <br>Devi solo essere migliore di quanto avresti mai pensato di poter essere",
"Se il futuro è davanti a te<br>dalle la possibilità di essere vissuto<br><br>Se l'incertezza è davanti a te<br>dalle la possibilità di diventare certezza<br><br>Se la ragione è davanti a te<br>dalle la possibilità di decidere con il cuore<br><br>Se l'amore è davanti a te<br>allora dagli tutte le possibilità del mondo<br>&#9825;",
"noNon bisogna fare tutto giusto nella vita...<br>sulla lapide<br>non ci sono voti<img src='img/lu1.jpg' class='img-circle'>",
"noPerché amare se stessi<br>fa volare anche le farfalle<br><img src='img/du_bist_ein_schmetterling.jpg'>",
"noFantastico è...<br>uıǝs nz ɥɔılʞɔülƃ ıǝqɐp pun uǝllǝʇs nz ɟdoʞ uǝp ɟnɐ ʇlǝʍ ǝıp nz pun qɐ<br><img src='img/umdrehen.jpg' class='img-circle'>", 
"Sii semplicemente<br>te stesso<br>",
"Ogni ora<br>ogni minuto della tua vita è un dono<br>Non rimandare nulla<br>che porti gioia alla tua vita<br>Perché non sai<br>&#8987;<br>quanto tempo ti rimane...",
"Dobbiamo capire<br><br>che la Terra è una scuola<br>dove dobbiamo imparare certe cose<br>ad esempio pazienza<br>tolleranza<br>lo sviluppo di capacità spirituali e creative e soprattutto amore<br>e questo significa <b>amore per se stessi</b> e per gli altri<br>L'amore è la materia principale in tutte le classi della scuola della vita<br>quindi il compito di apprendimento più importante e bello<br>&#9825;",
"noVuoi essere felice?<br><img src='img/glueck3.jpg' class='img-circle'><br>Allora non vivere nel passato<br>Non vivere nel futuro<br>ma vivi ora<br>in questo momento<br>e goditi questo momento unico<br>",
"noDio ti ha dato un volto<br>ma devi ridere da solo<br><img src='img/lachen_musst_selber.jpg' class='img-circle'>",
"noI miracoli iniziano<br>quando diamo ai nostri sogni<br><img src='img/glueck3.jpg' class='img-circle'>più energia che alle nostre paure",
"Dai a ogni giorno la possibilità di essere il più bello della tua vita",
"I tempi più difficili spesso ti conducono ai momenti più straordinari della tua vita. Mantieni la fede. Ne varrà la pena alla fine",
"Il coraggio sta all'inizio!<br>Non è mai troppo tardi per diventare ciò che avresti potuto essere.",
"Non puoi scegliere cosa succede nella vita, ma puoi scegliere come reagire. Non lasciare che il tuo presente sia determinato dal tuo passato e lascia che il passato sia un buon consigliere per il futuro",
"Tutto ciò che sei<br>tutto ciò che vuoi<br>tutto ciò che devi essere<br>parte da te stesso",
"Sei unico<br>Credi in te stesso<br>Ora e per sempre", 
"Ciò che pensi lo crei<br>Ciò che senti lo attiri<br>Ciò che immagini lo riceverai", 
"Non importa cosa fai, ognuno penserà comunque ciò che vuole di te, quindi fai ciò che il tuo cuore desidera e sii chi sei davvero, perché così ti sentirai a tuo agio con te stesso",
 "Prendi la tua vita nelle tue mani<br>Altrimenti lo faranno gli altri per te<br>", 
 "Tutto ciò di cui hai bisogno per avere successo è già dentro di te", 
 "Sii sempre coraggioso nel cambiare", 
 "Sii grato per ciò che hai<br> mentre lavori per ciò che desideri", 
 "Segui la tua strada e credi in te stesso<br>non importa cosa dicono gli altri", 
 "È la tua vita<br>Credi in te stesso",
 "Il momento presente è il tuo futuro",
 "Non smettere mai di sorridere. È meglio invecchiare con rughe sul viso che con rughe nel cuore",
 "Sei meraviglioso! NON DIMENTICARLO MAI",
 "Se guardi intorno a te e tutto è buio, guarda ancora una volta, forse sei tu la luce",
 "Non aver paura di invecchiare. Puoi ancora fare molte sciocchezze. Solo più lentamente.",
 "Cura i tuoi pensieri. Quello che pensiamo crescerà dentro di noi",
 "Sii il motivo per cui altre persone ricominciano a credere nel bene delle persone",
 "I desideri devono essere lasciati andare, per poter realizzarsi... nella LORO REALIZZAZIONE.",
 "Non serve possedere molto per dare tanto! Il gesto che viene dal cuore - è quello che conta!",
 "Bisogna aspettarsi di tutto. Anche il bene",
 "Credi in te stesso e non dubitare di ciò che fai, ma rifletti su ciò che vuoi veramente. Senza paura di ciò che potrebbe diventare. Perché ciò che è davanti a noi e ciò che è dietro di noi non è nulla in confronto a ciò che è dentro di noi. E quando portiamo fuori nel mondo ciò che è dentro di noi, accadono miracoli",
 "Sii audace, selvaggio e meraviglioso",
 "Chi dona gioia porta luce nei cuori solitari",
 "Un giorno la paura bussò alla porta. Il coraggio si alzò e aprì, ma non c'era nessuno fuori.",
 "Chi ha imparato a camminare nell'oscurità non ha bisogno di abbaglianti intorno a sé.",
 "Credi in te stesso! Nella tua vita hai già superato così tante difficoltà. RIUSCIRAI ANCHE QUESTA VOLTA!",
 "Il mondo appartiene a chi osa pensare in modo diverso",
 "Soffrirai finché reagirai emotivamente a tutto ciò che ti viene detto.<br>La vera forza risiede nel sedersi e guardare le cose con logica e calma.<br><br>Se le parole possono controllarti, significa che chiunque può controllarti.<br>Respira profondamente e lascia semplicemente andare alcune cose.<br><br>Bruce Lee",
 "Il futuro dipende da ciò che fai oggi.<br>",
 "I sogni possono cambiare il futuro. Ma solo quando apri gli occhi puoi realizzarli",
 "Strade difficili portano spesso a destinazioni meravigliose",
 "Ognuno deve credere in qualcosa. Perché non credere in se stessi?",
 "Non smettere mai di sorridere. È meglio invecchiare con rughe sul viso che con rughe nel cuore.",
 "Se sapessi quanto sono potenti i tuoi pensieri, non penseresti mai più negativamente!",
 "Come hai saputo che ce l'avresti fatta? <br><br><br>Non lo sapevo.<br>Lo volevo!!!",
 "Lascia che la vita faccia il suo corso e fidati di essa",
 "noLe persone migliori sono quelle con la testa piena di stranezze, <img src='img/t194.jpg' class='img-circle'>con il coraggio nelle vene e il cuore nel posto giusto",
 "Per superare le tue paure devi attraversarle e non aggirarle.",
 "Chi non ha il coraggio di affrontare le paure, non può crescere.",
 "Sii realistico, pianifica un miracolo",
 "La felicità è quando sei soddisfatto di te stesso<br> e non hai bisogno della conferma degli altri.",
 "Non è colpa tua per la programmazione che hai ricevuto da bambino.<br><br>Da adulto, però, è tua completa responsabilità correggerla.",
 "noLe persone migliori sono quelle con la testa piena di stranezze, <img src='img/t194.jpg' class='img-circle'>con il coraggio nelle vene e il cuore nel posto giusto",
 "Rimani fiducioso in te stesso e nel tuo centro dorato",
 "Trova il <b>coraggio</b> per il cambiamento che desideri,<br><br>la <b>forza</b> per portarlo avanti<br><br>e la <b>fede</b> che tutto si trasformerà in meglio.",
 "Non puoi tornare indietro e cambiare l'inizio.<br><br>Ma puoi iniziare ora e cambiare la fine!",
 "Cose meravigliose accadranno non appena ti allontanerai dal negativo!",
 "Come si diventa una farfalla?<br><br>...chiese pensierosa il bruco.<br><br>DEVI VOLERLO COSÌ TANTO DA ESSERE DISPOSTO A LASCIARE ANDARE LA TUA ESISTENZA COME BRUCO.",
 "E arrivò il giorno in cui il rischio di restare in boccio divenne più doloroso che sbocciare!",
 "Non hai bisogno di un insegnante che ti influenzi.<br><br><br>Hai bisogno di un insegnante che ti insegni a non lasciarti più influenzare.",
 "Onora le tue debolezze e cicatrici con l'oro dell'❤️ amore per te stesso",
 "L'amore ❤️ di Dio è riversato nel tuo cuore",
 "Credi nei miracoli, nell'amore e nella fortuna<br>Guarda avanti<br><br>Fai ciò che vuoi e sii fiero di farlo, perché questa vita la vivi solo tu!",
 "Non dare al tuo passato il potere di influenzare il tuo futuro!<br><br>Lascia andare, il tuo passato non ha nulla di nuovo da dirti.",
 "La tua vera ricchezza sono i tuoi pensieri!",
 "Puoi essere una brava persona con un cuore amorevole e dire comunque 'no'.",
 "Un uccello non ha mai paura che il ramo sotto di lui possa rompersi.<br><br>Non perché si fida del ramo, ma delle sue ali.<br><br>Non perdere mai la fiducia in te stesso.",
 "Puoi e devi pensare ciò che vuoi. Il tuo volere sia fatto."
];

var motivationTextRu = [
"Никогда не сдерживай комплименты. Для этого нет причин",
"Ты сам несешь ответственность за свои мысли и свою жизнь. Ты силен и полон энергии",
"Будь добр к себе",
"Дикие волки <img src='img/wolf.jpg' class='img-circle'> и естественные женщины имеют много общего: точность их инстинктивной интуиции, склонность к игривости и непреклонную преданность<br><br>Кларисса Пинкола Эстес",
"Не позволяй угасать своему сиянию, даже если оно ослепляет других!",   
"Как хорошо и ценно, что ты есть",    
"Твое истинное богатство — это твои мысли.",
"<img src='img/erster.png'> Стремись быть первым: первым кивнуть, первым улыбнуться, первым сделать комплимент и первым простить.", 
"Ты сам собой, когда не подвергаешь сомнению свои действия", 
"Не жди, чтобы люди улыбнулись тебе, <img src='img/zeigeesihnen.jpg'> покажи им, как это делается!", 
"Учиться на ошибках до тех пор, пока ты их больше не совершаешь.<img src='img/lernen.jpg' class='img-circle'>", 
"Вдох<br>Выдох<br>Счастье<img src='img/gluecklich1.jpg' class='img-circle'>", 
"Ты способен мотивировать себя на действия.<br><img src='img/doit.png' class='img-circle'> Просто сделай это!", 
"Любое, даже самое длинное путешествие, начинается с первого шага<img src='img/doit.png' class='img-circle'>", 
"Печаль не стоит того. <img src='img/neuanfang.jpg'> Когда полубоги уходят, приходят боги", 
"Знал ли ты, что бабочке невозможно увидеть свои собственные крылья?<br> Знал ли ты также, что ее крылья считаются одним из самых красивых достижений природы?<br>Она не видит, какая она красивая, но все остальные видят это.<br>То же самое и с нами, людьми.<img src='img/butterfly1.jpg'>",
"Держи солнце в своем сердце, несмотря на штормы или снег, несмотря на небо, полное облаков, или землю, полную конфликтов — держи солнце в своем сердце, и это озарит твой самый темный день<img src='img/sun.jpg' class='img-circle'>",
"Что бы ни происходило. Верь в себя!<br>Что бы ни происходило. Оставайся верен себе!<br>Что бы ни происходило. Люби себя!", 
"И снова и снова верить в себя — вот секрет богов.", 
"Счастье кроется в действии и поступках.", 
"Упорство — это тайная сила успешных. Будь несломим.", 
"Я благодарен за камни, которые мне бросали под ноги.<img src='img/steine.jpg' class='img-circle'> Без них я бы не нашел своих сил.", 
"<b>Ты никогда не сможешь впечатлить всех своими действиями.</b><br>Даже если ты пойдешь по воде, найдется тот, кто спросит, почему ты не умеешь плавать.", 
"Не трать так много энергии на негатив.<img src='img/bogen1.jpg' class='img-circle'> Сосредоточься на своей позитивной цели и на том, чего хочешь достичь.<img src='img/bogen2.jpg' class='img-circle'>", 
"Полюби себя таким, какой ты есть, а не таким, каким тебя хотят видеть другие.", 
"Ты чудесный", 
"Судьба всегда в том, что ты делаешь из нее", 
"Будь просто счастлив в настоящем<img src='img/t161.jpg' class='img-circle'>", 
"Перестань сравнивать себя, улыбнись в зеркало", 
"Подумай о своих мечтах, они скучают по тебе.", 
"Будь просто счастлив в настоящем", 
"Если одуванчик может пробиться сквозь асфальт, то ты уж точно найдешь свой путь!<img src='img/loewenzahn.jpg' class='img-circle'>", 
"Я решил больше не ждать лучших времен.<br>Лучшие времена — это сейчас.<br>Я сделаю оставшиеся годы своей жизни самыми счастливыми.<img src='img/jetzt.jpg' class='img-circle'><br>Потому что жизнь принадлежит мне, и она слишком коротка, чтобы ждать дольше.", 
"Что бы ни происходило в твоей жизни, верь в самого важного человека — в себя", 
"Наслаждайся своей жизнью. Утраченного времени не вернуть. Живи в своей мечте и никогда не отказывайся от ее осуществления", 
"Жизнь — это приключение: живи, чувствуй, люби, смейся, плачь, играй, выигрывай, проигрывай, споткнись... но всегда поднимайся и продолжай идти своим путем", 
"Никогда не считай, что что-то слишком мелочно для того, чтобы изменить твою жизнь.<br>Это может быть твоим счастьем.", 
"Танцуй, пой и свисти, когда только захочешь<br>ведь однажды ты услышишь лишь тишину из своей могилы", 
"Всегда оставайся верен себе, со всеми своими желаниями и мечтами. Не меняйся и следуй своим путем. Прости себе свои слабости с любовью и стань сильным.",
"Ставь себе цели<br>разделяй их на этапы<br>и иди шаг за шагом",
"Между ушами выигрывают или проигрывают",
"Мир принадлежит тем, кто отправляется на его завоевание<br>вооружённый любовью и хорошим настроением",
"Наслаждайся моментом<br>ведь момент<br>это твоя жизнь",
"Тебе не нужно быть лучше всех остальных<br>Тебе нужно быть лучше, чем ты когда-либо думал, что можешь быть",
"Если будущее перед тобой<br>дай ему шанс быть прожитым<br><br>Если неопределённость перед тобой<br>дай ей шанс стать определённостью<br><br>Если разум перед тобой<br>дай ему шанс принять решение сердцем<br><br>Если любовь перед тобой<br>тогда дай ей все шансы на свете<br>&#9825;",
"В жизни не обязательно всё делать правильно...<br>на надгробии<br>оценок не пишут<img src='img/lu1.jpg' class='img-circle'>",
"Любить себя<br>значит позволить бабочкам летать<br><img src='img/du_bist_ein_schmetterling.jpg'>",
"Круто, когда...<br>˙ʞɔılʞɔuılƃ ǝqɐp uʍop əu ʎʇəɹ ǝıp<br><img src='img/umdrehen.jpg' class='img-circle'>",
"Будь просто<br>собой<br>",
"Каждый час<br>каждая минута в твоей жизни — это подарок<br>Не откладывай<br>то, что приносит радость в твою жизнь<br>Ведь ты не знаешь<br>&#8987;<br>сколько времени у тебя осталось...",
"Мы должны понимать<br><br>что Земля — это школа<br>где мы должны научиться определённым вещам<br>например, терпению<br>снисходительности<br>развитию духовных и творческих способностей, а главное любви<br>а это значит <b>любви к себе</b> и другим<br>Любовь — это главный предмет во всех классах школы жизни<br>поэтому это самая важная и прекрасная задача для обучения<br>&#9825;",
"Хочешь быть счастливым?<br><img src='img/glueck3.jpg' class='img-circle'><br>Тогда не живи в прошлом<br>Не живи в будущем<br>а живи сейчас<br>в этот момент<br>и наслаждайся этим уникальным мгновением<br>",
"Бог дал тебе лицо<br>но смеяться ты должен сам<br><img src='img/lachen_musst_selber.jpg' class='img-circle'>",
"Чудеса начинаются тогда<br>когда мы даём своим мечтам<br><img src='img/glueck3.jpg' class='img-circle'>больше энергии<br>чем своим страхам",
"Дай каждому дню шанс стать самым прекрасным в твоей жизни",
"Самые трудные времена часто приводят к самым великим моментам твоей жизни. Сохрани веру. Всё будет того стоить в итоге",
"Смелость стоит в начале!<br> Никогда не поздно стать тем, кем ты мог бы быть.",
"Ты не можешь выбрать, что случается в жизни, но можешь выбрать, как с этим справляться. Не позволяй прошлому диктовать твоё настоящее и используй прошлое как советчика для будущего",
"Всё, что ты есть<br>всё, чего ты хочешь<br>всё, что ты должен<br>исходит из тебя самого",
"Ты уникален<br>Верь в себя<br>Сейчас и навсегда",
"То, что ты думаешь, ты создаёшь<br>То, что ты чувствуешь, ты притягиваешь<br>То, что ты представляешь, ты получаешь",
"Что бы ты ни делал, все всё равно думают о тебе своё, поэтому сразу делай то, что хочешь от сердца, и будь собой, ведь тогда ты будешь чувствовать себя комфортно с собой",
"Возьми свою жизнь в свои руки<br>иначе её возьмут другие",
"Всё, что тебе нужно для успеха, уже есть в тебе",
"Будь смелым снова и снова меняться",
"Будь благодарен за то, что у тебя есть<br>пока работаешь над тем, что хочешь",
"Иди своим путём и верь в себя<br>не важно, что говорят другие",
"Это твоя жизнь<br>Верь в себя",
"Настоящий момент — это твоё будущее",
"Никогда не переставай улыбаться. Лучше постареть с морщинами на лице, чем с морщинами на сердце",
"Ты замечательный! НИКОГДА ЭТО НЕ ЗАБУДЬ",
"Если ты смотришь вокруг и всё темно, посмотри ещё раз, возможно, ты сам являешься светом",
"Не бойся старости. Ты всё ещё можешь делать глупости. Только медленнее.",
"Следи за своими мыслями. То, что мы думаем, растёт в нас",
"Будь тем, благодаря кому другие снова поверят в хорошее в людях",
"Мечты нужно отпускать, чтобы они могли исполниться...",
"Не обязательно много иметь, чтобы много давать! Главное — жест, идущий от сердца!",
"Будь готов ко всему. Даже к хорошему.",
"Верь в себя и не сомневайся в том, что ты делаешь, а думай о том, чего ты действительно хочешь. Без страха перед тем, что из этого получится. Потому что то, что впереди и позади нас, ничто по сравнению с тем, что внутри нас. И если мы проявим то, что внутри, в мире произойдут чудеса.",
"Будь дерзким, диким и удивительным",
"Однажды страх постучался в дверь. Смелость встала и открыла, но снаружи никого не было.",  
"Кто научился ходить в темноте, тому не нужны ослепляющие огни вокруг.",  
"Верь в себя! Ты уже столько всего преодолел в своей жизни. Ты справишься и на этот раз!",  
"Мир принадлежит тем, кто осмеливается мыслить иначе.",  
"Ты будешь страдать до тех пор, пока эмоционально реагируешь на всё, что тебе говорят.<br>Истинная сила заключается в том, чтобы откинуться назад и рассмотреть всё с логикой и спокойствием.<br><br>Если слова могут тобой управлять, значит, любой может тобой управлять.<br>Сделай вдох и позволь чему-то просто уйти.<br><br>Брюс Ли",  
"Будущее зависит от того, что ты делаешь сегодня.<br>",  
"Мечты могут изменить будущее. Но только открыв глаза, их можно воплотить в жизнь.",  
"Трудные дороги часто ведут к прекрасным целям.",  
"Каждому нужно во что-то верить. Так почему бы не верить в себя?",  
"Никогда не переставай улыбаться. Лучше состариться с морщинами на лице, чем с морщинами на сердце.",  
"Если бы ты знал, насколько сильны твои мысли, ты бы никогда больше не думал негативно!",  
"— Откуда ты знал, что у тебя получится?<br><br><br>— Я не знал.<br>Я хотел этого!",  
"Просто позволь жизни идти своим чередом и доверься ей.",  
"Чтобы преодолеть свои страхи, нужно пройти через них, а не обходить их.",  
"Кто не имеет смелости пережить свои страхи, не сможет расти.",  
"Будь реалистом, планируй чудо.",  
"Счастье — это когда ты доволен собой<br> и не нуждаешься в подтверждении от других.",  
"Ты не виноват в том, как тебя запрограммировали в детстве.<br><br>Но во взрослом возрасте это полностью твоя ответственность — всё исправить.",  
"Оставайся верным себе и своему внутреннему равновесию.",  
"Найди <b>смелость</b> для желаемых перемен,<br><br><b>силу</b> их осуществить<br><br>и <b>веру</b> в то, что всё изменится к лучшему.",  
"Ты не можешь вернуться назад и изменить начало.<br><br>Но ты можешь начать сейчас и изменить конец!",  
"Прекрасные вещи происходят, как только ты отстраняешься от негатива!",  
"Как стать бабочкой?<br><br>— задумчиво спросила гусеница.<br><br>ТЫ ДОЛЖЕН ТАК СИЛЬНО ХОТЕТЬ ЭТОГО, ЧТО БУДЕШЬ ГОТОВ ОТКАЗАТЬСЯ ОТ СВОЕГО СУЩЕСТВОВАНИЯ КАК ГУСЕНИЦА.",  
"И настал день, когда риск остаться в бутоне стал более болезненным, чем желание расцвести!",  
"Тебе не нужен учитель, который тебя влияет.<br><br><br>Тебе нужен учитель, который научит тебя больше не поддаваться влиянию.",  
"Почитай свои слабости и шрамы золотом твоей ❤️ любви к себе.",  
"Любовь ❤️ Бога излита в твоё сердце.",  
"Верь в чудеса, любовь и счастье.<br>Смотри вперёд.<br><br>Делай то, что хочешь, и будь собой, ведь эту жизнь проживаешь только ты!",  
"Не позволяй своему прошлому влиять на твоё будущее!<br><br>Отпусти его, прошлое не скажет тебе ничего нового.",  
"Твои истинные богатства — это твои мысли!",  
"Ты можешь быть хорошим человеком с любящим сердцем и всё равно говорить «нет».",  
"Птица никогда не боится, что ветка под ней сломается.<br><br>Не потому что она доверяет ветке, а потому что верит своим крыльям.<br><br>Никогда не теряй веру в себя.",  
"Ты можешь и должен думать то, что хочешь. Да будет твоя воля."
];


    
var motivationText = [
"Der grösste Fehler den man im Leben machen kann, ist immer Angst zu haben, ein Fehler zu machen",
"Halte niemals Komplimente zurück. Dafür gibt es keinen Grund",
"Du übernimmst jetzt selbst die Verantwortung für Dein Denken und Leben. Du bist kraftvoll und dynamisch",
"Sei gut zu Dir selbst",
"noFrei lebende Wölfe<img src='img/wolf.jpg' class='img-circle'>und ungekünstelte Frauen haben vieles gemeinsam: die Akkuratheit ihres instinktiven Feingefühls, eine Vorliebe für alles Spielerische und eine schier unverrückbare Loyalität<br><br>Clarissa Pinkola Estes",
"Lass Dir Dein Leuchten nicht nehmen, nur weil es andere blenden könnte!",   
"Es ist so wertvoll und schön dass es Dich gibt",    
"Dein wahrer Reichtum sind Deine Gedanken.",
"<img src='img/erster.png'>Strebe danach, Erster zu sein: Als Erster zu nicken, als Erster zu lächeln, als Erster ein Kompliment zu machen und als Erster zu vergeben.","Du bist Du selbst, wenn Du Deine Handlungen nicht mehr HINTERFRAGST","Warte nicht darauf dass die Menschen Dich anlächeln, <img src='img/zeigeesihnen.jpg'>zeige es Ihnen wie es geht!","Aus Fehlern solange zu lernen, bis Du sie nicht mehr machst.<img src='img/lernen.jpg' class='img-circle'>","Einatmen<br>Ausatmen<br>Glücklichsein<img src='img/gluecklich1.jpg' class='img-circle'>","noDu hast die Fähigkeit Dich zum Handeln zu motivieren.<br><img src='img/doit.png' class='img-circle'> Tue es einfach!","Jede, auch noch so lange Reise, beginnt mit dem ersten Schritt<img src='img/doit.png' class='img-circle'>","Liebeskummer lohnt sich nicht. <img src='img/neuanfang.jpg'> Wenn Die Halbgötter gehen kommen die Götter","no<img src='img/butterfly.jpg' class='img-circle'>Wusstest Du, dass es für einen Schmetterling unmöglich ist, seine eigenen Flügel zu sehen?<br> Wusstest Du auch, dass seine Flügel als eine der schönsten Errungenschaften in der Natur gelten?<br>Er kann nicht sehen wie schön sie sind, aber alle anderen können es.<br>Genauso ist es bei uns Menschen<img src='img/butterfly1.jpg'>",
"no<img src='img/sun1.jpg' class='img-circle'>Hab Sonne im Herzen, egal ob es stürmt oder schneit, ob der Himmel voll Wolken, die Erde voll Streit - hab Sonne im Herzen, dann komme was mag, das leuchtet voll Licht dir den dunkelsten Tag<img src='img/sun.jpg' class='img-circle'>",
"Egal was passiert.Glaube an Dich!<br>Egal was passiert.Bleib Dir treu!<br>Egal was passiert.Habe Dich lieb!<br>","Und immer wieder an Dich selber zu glauben ist das Geheimnis der Götter.","Glück liegt auch im Handeln und Tun.","Beharrlichkeit ist die geheime Stärke des Erfolgreichen. Sei unerschütterlich.","noIch bin dankbar für die Steine die mir in den Weg gelegt wurden.<img src='img/steine.jpg' class='img-circle'>Ohne Sie wäre ich sonst nicht über meine Stärken gestolpert.","<b>Du kannst nie alle mit Deinem Tun begeistern.</b><br>Selbst wenn Du übers Wasser laufen kannst, kommt einer daher und fragt ob Du zu blöd zum Schwimmen bist.","noVerwende nicht so viel Energie auf das Negative.<img src='img/bogen1.jpg' class='img-circle'>Fokussiere dich auf Dein positives Ziel und das, was du erreichen willst.<img src='img/bogen2.jpg' class='img-circle'>","Fange an Dich zu lieben wie Du bist und nicht wie Dich Andere gern sehen würden.","Du bist WUNDERBAR","Schicksal ist immer was du daraus machst","Sei einfach glücklich im Jetzt<img src='img/t161.jpg' class='img-circle'>","Hör auf Dich zu vergleichen, lächle in den Spiegel","Denke an Deine Träume, sie vermissen Dich.","Sei einfach glücklich im Jetzt","no<img src='img/loewenzahn.jpg' class='img-circle'><br>Wenn es ein Löwenzahn durch den Asphalt schafft, dann wirst Du doch sicher auch einen Weg finden!",
"noIch habe entschieden nicht länger auf bessere Zeiten zu warten.<br>Die besten Zeiten sind jetzt.<br>Ich mache die restlichen Jahre meines Lebens zu den glücklichsten.<img src='img/jetzt.jpg' class='img-circle'><br>Denn das Leben gehört mir und es ist einfach zu kurz um noch länger zu warten.",
"Egal in was für einer Lebenslage Du dich gerade befindest. Glaube an den wichtigsten Menschen = DICH",
"Genieße Dein Leben. Verlorene Zeit kehrt niemals zurück. Lebe in Deinem Traum und gebe niemals auf ihn zu verwirklichen","Das Leben ist wie ein Abenteuer, lebe, fühle, liebe, lache, weine, spiele, gewinne, verliere, stolpere...doch erhebe Dich immer wieder und gehe Deinen Weg",
"Sei dir nie zu schade etwas zu unternehmen was dein leben verändern würde.<br>Es könnte dein Glück sein.",
"Tanze singe und pfeife wann immer Du Lust danach hast<br>denn irgendwann hörst Du nur noch die Stille von Deinem Grab",
"Bleib Dir immer selbst treu, mit all Deinen Wünschen und Träumen. Verstell Dich nicht und geh Deinen Weg. Vergebe Dir Deine Schwäche mit Liebe und sei dadurch stark.",
"Dieser Moment ist einzigartig und kommt nie wieder zurück. Warte nicht auf den perfekten Moment. Mache ihn dir perfekt.",
"Heute ist der erste Tag vom Rest Deines Lebens.",
"In Liebe vergebe ich mir meine Schwäche und bin dadurch stark",
"Erkenne daß im heutigen Tag Deine Chance liegt",
"Du bist immer selbst dein Lehrer",
"Perfektion ist kotzlangweilig und hält dich davon ab mit deiner Sache fertig zu werden",
"Es gibt nichts größeres als an Dich zu glauben!",
"Glück entsteht durch deine Art zu Denken",
"Gott hört auf die Gedanken",
"Du kannst entweder deine VISIONEN oder deine Ängste leben",
"Die Angst hat ihren Anfang im Kopf<br>Der Mut allerdings auch", "noDeine Motivations Maschine<img src='img/motivationsmaschine.jpg' class='img-circle'>",
"So jung wie heute wirst Du nie wieder<br>in Deinem Leben!",
"Du bist ein Gewinner!", "Glaube an Dich",
"Heute ist ein Geschenk<br> und der einzigste Tag<br>an dem Du etwas verändern kannst",
"Gebe nie<br>nie<br>niemals auf<br><br>und habe die Ausdauer zum Erfolg!",
"Habe den Mut zu Risiken<br>denn nur durch diesen Mut<br>kannst Du an wahrer Größe gewinnen",
"Der Humor ist der Vater &#9786;<br>das Lachen die Mutter<br>eines glücksgemütlichen Menschen<br><img src='img/humor.jpg' class='img-circle'>",
"Sei bei allem dankbar<br>Auch für Dein Problem<br>denn dies ist der Dünger<br>für Dein Wachstum!",
"Die Liebe ist nicht nur das Fundament aller Dinge <br>&#9825;sie ist viel mehr<br>&#9825;<br>sie ist auch der Gipfel aller Dinge",
"Willst Du ein Wunder in Dein Leben ziehen<br><br>so entlasse die Angst und den Zweifel<br>aus Deinen Gedanken",
"Die Richtung Deines Denkens und Tuns<br>halte stets nach vorne in die Zukunft<br><br>denn Dein Schöpfer gab Dir die Augen vorne",
"Ein wahrer Freund beflügelt Dich immer<br>von einem Gipfel zum anderen zu kommen.<br>Du kannst Dir Deine Freunde aussuchen",
"Glaube an Dich<br><br>Glaube daran dass die göttliche Energie immer in Dir<br>und für Dich ist<br>",
"Sei immer Du selbst<br>im Jetzt und Hier<br>mache Dir und anderen Komplimente<br>mache Dich und andere zu Riesen",
"Der Schlüssel &#9825;<br>zu Deinem Glück<br>liegt in Dir",
"Mit dem Herzen an Dein Ziel glauben<br> das ist das Geheimnis der Götter",
"Du bist der wichtigste Mensch in Deinem Leben<br>deshalb habe Dich lieb &#9825;<br>und respektiere Dich", "no<img src='img/glueck3.jpg' class='img-circle'><br>Glück hängt nicht davon ab<br>wer Du bist oder was Du hast<br>es hängt nur davon ab<br>was Du denkst",
"Schmerz und Anstrengung<br>sind die Leitersprossen<br>zum Erfolg",
"Du bist<br>&#9825;<br>einzigartig", "Wenn Du die Liebe lebst<br>&#x1f496;<br>dann hat die Angst angst und sie flüchtet",
"Deine Gedanken<br>sind die Nahrung<br>für Deine Seele<br>",
"Du allein<br>bist der Dirigent<br>Deines Lebens&nbsp;&#9835;",
"Reinige Dein Leben<br>durch die Reinigung<br>Deiner Gedanken",
"Wichtig ist nicht wo Du jetzt stehst oder woher Du kommst<br>entscheidend ist wohin Du willst",
"noHöre nie auf zu lächeln<br><img src='img/lachen_musst_selber.jpg' class='img-circle'><br>auch dann nicht wenn Du sehr traurig bist<br>denn Du weisst nicht wer sich vielleicht in Dein Lächeln verliebt<br>",
"noWenn andere denken Du bist am Ende<br><img src='img/weiter1.jpg' class='img-circle'><br>so fange erst richtig an",
"noWenn Gott Dir ein besonderes Geschenk machen will<br>verpackt er es in ein Problem<br><img src='img/problem_ist_ein_geschenk.jpg'>",
"Glaube an Dich<br>denn wenn Du es nicht tust<br>wer soll dann an Dich glauben?<br>",
"noDu bist ein Diamant<br><img src='img/du_bist_ein_diamant1.jpg' class='img-circle'><br>und der Schleifstein dazu",
"Wunder geschehen<br><br>wenn Du Deine Gedanken<br>von allen Ängsten und Zweifeln<br>reinigst",
"Lasse los<br>und werde dadurch<br>reicher",
"noHabe den Mut<br>die Hürden Deines Lebens<br>zu meistern<br><img src='img/hindernis.jpg' class='img-circle'>",
"Je mehr Selbstliebe du ausstrahlst<br>umso mehr wohl gestimmte Menschen und positive Situationen<br>ziehst Du an<br>",
"Setze Dir Ziele<br>teile sie in Etappen ein<br>und gehe Schritt für Schritt ",
"Zwischen den Ohren  wird gewonnen oder verloren",
"Die Welt gehört denen, die zu Ihrer Eroberung ausziehen<br>bewaffnet mit Liebe und guter Laune",
"Genieße den Augenblick<br>denn der Augenblick<br>ist Dein Leben  ",
"Du musst nicht besser sein als jeder andere <br>Du musst nur besser sein als Du jemals gemeint hast sein zu können",
"Wenn die Zukunft vor Dir steht<br>gib ihr die Chance erlebt zu werden<br><br>Wenn die Ungewissheit vor Dir steht<br>gib ihr die Chance Gewissheit zu werden<br><br>Wenn die Vernunft vor Dir steht<br>gib ihr die Chance aus dem Bauch zu entscheiden<br><br>Wenn die Liebe vor Dir steht<br>dann gib ihr jede Chance der Welt<br>&#9825;",
"noMan muss im Leben nicht alles richtig machen...<br>auf dem Grabstein<br>stehen keine Noten<img src='img/lu1.jpg' class='img-circle'>",
"noDenn sich selbst zu lieben<br>lässt auch Schmetterlinge fliegen<br><img src='img/du_bist_ein_schmetterling.jpg'>",
"noGeil ist...<br>uıǝs nz ɥɔılʞɔülƃ ıǝqɐp pun uǝllǝʇs nz ɟdoʞ uǝp ɟnɐ ʇlǝʍ ǝıp nz pun qɐ<br><img src='img/umdrehen.jpg' class='img-circle'>", "Sei einfach<br>Du<br>selbst<br>",
"Jede Stunde<br>jede Minute in Deinem Leben ist ein Geschenk<br>Verschiebe nichts<br>was Deinem Leben Freude bereitet<br>Denn Du weißt nicht<br>&#8987;<br>wieviel Zeit Dir noch bleibt...",
"Wir müssen verstehen<br><br>dass die Erde eine Schule ist<br>in der wir bestimmte Dinge zu lernen haben<br> beispielsweise Geduld<br>Nachsicht<br>die Entwicklung geistiger und schöpferische Fähigkeiten und vor allem Liebe<br>und das heisst <b>Liebe zu sich selbst</b> und zu anderen<br>Liebe ist in allen Klassen der Lebensschule das Hauptfach<br>also somit die wichtigste und schönste Lernaufgabe<br>&#9825;",
"noWillst Du glücklich sein?<br><img src='img/glueck3.jpg' class='img-circle'><br>Dann lebe nicht in der Vergangenheit<br>Lebe nicht in der Zukunft<br>sondern lebe jetzt<br>in diesem Augenblick<br>und genieße diesen einzigartigen Moment<br>",
"noGott hat Dir ein Gesicht gegeben<br>doch Lachen musst Du selber<br><img src='img/lachen_musst_selber.jpg' class='img-circle'>",
"noWunder beginnen dann<br>wenn wir unseren Träumen<br><img src='img/glueck3.jpg' class='img-circle'>mehr Energie geben<br>als unseren Ängsten",
"Gib jedem Tag die Chance der Schönste in Deinem Leben zu werden",
"Die härtesten Zeiten leiten Dich oft zu den grossartigsten Momenten Deines Lebens. Bewahre den Glauben. Alles wird es wert sein am Ende", "Mut steht am Anfang!<br> Es ist nie zu spät das zu werden was man hätte sein können.",
"Du kannst Dir nicht aussuchen was im Leben alles passiert aber Du kannst Dir aussuchen wie Du damit umgehst. Lass Dir Deine Gegenwart nicht von Deiner Vergangenheit bestimmen und lass die Vergangenheit ein guter Ratgeber für die Zukunft sein",
"Alles was Du bist<br>alles was Du willst<br>alles was Du sollst<br>geht von Dir selbst aus",
"Du bist einzigartig<br>Glaube an Dich<br>Jetzt und für immer", 
"Was Du denkst erschaffst Du<br>Was Du fühlst ziehst Du an<br>Was Du Dir vorstellst wirst Du bekommen", 
"Egal was Du tust jeder denkt sowieso von Dir was er will, deshalb kannst Du gleich tun was Du von Herzen willst und der sein, der Du wirklich bist, denn dann fühlst Du Dich mit Dir selbst wohl",
 "Nimm Dein Leben selbst in die Hand<br>Sonst werden es andere für Dich tun<br>", 
 "Alles was Du brauchst um erfolgreich zu sein hast Du bereits in Dir", 
 "Sei immer wieder mutig Dich zu verändern", 
 "Sei dankbar für das was du hast<br> während du für das arbeitest<br>was du willst", 
 "Geh deinen Weg und glaub an dich<br>egal was andere sagen", 
 "Es ist Dein Leben<br>Glaube an Dich",
 "Der jetzige Augenblick ist Deine Zukunft",
 "Höre nie auf zu lächeln. Es ist besser mit Falten im Gesicht alt zu werden, als mit Falten auf dem Herzen",
 "Du bist wundervoll! VERGISS DAS NIE",
 "Wenn Du dich umschaust und alles ist dunkel, schau noch einmal, vielleicht bist Du das Licht",
 "Hab nie Angst vor dem Altwerden. Du kannst immer noch viel Unsinn machen. Nur langsamer.",
 "Pflege Deine Gedanken. Was wir denken, wird in uns wachsen",
 "Sei der Grund, warum andere Menschen wieder an das Gute im Menschen glauben",
 "Wünsche muss man loslassen, damit sie gehen können. Nämlich in ERFÜLLUNG...",
 "Man muß nicht viel besitzen um viel geben zu können! Die Geste die vom Herzen kommt - die macht's aus!",
 "Man muß mit allem rechnen. Auch mit dem Guten",
 "Glaube an Dich und zweifle nicht an dem was Du tust, sondern denke darüber nach was Du wirklich willst. Ohne Angst vor dem, was daraus werden könnte. Denn was vor uns liegt und was hinter uns liegt, ist nichts im Vergleich zu dem, was in uns liegt. Und wenn wir das was in uns liegt nach außen in die Welt tragen, geschehen Wunder",
 "Sei frech und wild und wunderbar",
 "Wer Freude schenkt bringt Licht in einsame Herzen",
 "Eines Tages klopfte die Angst an die Tür. Der Mut stand auf und öffnete, aber da war niemand draußen.",
 "Wer gelernt hat im Dunkeln zu laufen, der braucht auch keine Blender um sich.",
 "Glaube an Dich! Du hast in deinem Leben schon so vieles GEMEISTERT. DU WIRST ES AUCH DIESMAL SCHAFFEN!",
 "Die Welt gehört denen, die sich trauen anders zu denken",
 "Du wirst leiden, solange Du eine emotionale Reaktion auf alles hast was zu Dir gesagt wird.<br>Wahre Kraft liegt darin, Dich zurück zu lehnen und die Dinge mit Logik & Ruhe zu betrachten.<br><br>Wenn Worte Dich kontrollieren können, bedeutet das, dass jeder Dich kontrollieren kann.<br>Atme durch und erlaube manches einfach los zu lassen.<br><br>Bruce Lee",
 "Die Zukunft hängt davon ab, was Du heute tust.<br> ",
 "Träume können die Zukunft verändern. Doch erst wenn man die Augen öffnet, kann man sie verwirklichen",
 "Schwierige Straßen führen oft zu wunderschönen Zielen",
 "Jeder muss an etwas glauben. Warum dann nicht an sich selbst?",
 "Hör nie auf zu lächeln. Es ist besser, mit Falten im Gesicht alt zu werden, als mit Falten auf dem Herzen.",
 "Wenn Du weisst wie mächtig Deine Gedanken sind, wirst Du nie wieder negativ denken!",
 "Woher wusstest Du, dass Du es schaffst? <br><br><br>Ich wusste es nicht.<br>Ich wollte es!!!",
 "Lass das Leben doch einfach mal machen und vertraue ihm",
 "noDie besten Menschen sind die, mit Flausen im Kopf, <img src='img/t194.jpg' class='img-circle'>dem Arsch in der Hose und dem Herz am rechten Fleck",
 "Um Deine Ängste zu überwinden musst Du Durch Sie hindurch und nicht um sie herum.",
 "Wer nicht den Mut hat, Ängste zu durchleben, kann nicht wachsen.",
 "Sei realistisch, plane ein Wunder",
 "Glück ist, wenn Du mit Dir selbst zufrieden bist<br> und dafür nicht die Bestätigung anderer brauchst.",
 "Du bist nicht schuld für die Programmierung, welche Du als Kind erfahren hast.<br><br>Als Erwachsener liegt es jedoch in DEINER vollen Verantwortung, um es wieder in Ordnung zu bringen.",
 "noDie besten Menschen sind die, mit Flausen im Kopf, <img src='img/t194.jpg' class='img-circle'>dem Arsch in der Hose und dem Herz am rechten Fleck",
 "Bleibe im Vertrauen zu Dir selbst und in Deiner goldenen Mitte",
 "Finde den <b>Mut</b> für die Veränderung, die Du Dir wünschst,<br><br>die <b>Kraft</b> es durchzuziehen<br><br>und den <b>Glauben</b> daran, dass sich alles zum Besten wenden wird.",
 "Du kannst nicht zurück gehen und den Anfang ändern.<br><br>Aber Du kannst jetzt neu Anfangen und das Ende ändern!",
 "Wunderschöne Dinge werden passieren, sobald Du Dich von dem Negativem Distanzierst!",
 "Wie wird man ein Schmetterling?<br><br>...fragte die Raupe nachdenklich.<br><br>DU MUSST SO SEHR WOLLEN, DASS DU BEREIT BIST, DEINE EXISTENZ ALS RAUPE AUFGEBEN ZU WOLLEN.",
 "Und es kam der Tag, an dem das Risiko, in der Knospe zu verharren, schmerzlicher wurde als zu erblühen!",
 "Du brauchst keinen Lehrer, der Dich beeinflusst.<br><br><br>Du brauchst einen Lehrer, der Dich lehrt, Dich nicht mehr beeinflussen zu lassen.",
 "Ehre Deine Schwächen und Narben mit dem Gold Deiner ❤️ Selbstliebe",
 "Die Liebe ❤️ Gottes ist ausgegossen in Dein Herz",
"Glaube an Wunder, Liebe & Glück<br>Schaue nach vorne<br><br>Tue, was Du willst und stehe dazu, denn dieses Leben lebst nur Du!",
"Gib Deiner Vergangenheit nicht die Macht, Deine Zukunft zu beeinflussen!<br><br>Lass sie los, Deine Vergangenheit hat Dir nichts Neues zu sagen.",
"Dein wahrer Reichtum sind Deine Gedanken!",
"Du kannst ein guter Mensch mit einem liebevollen Herz sein und trotzdem 'nein' sagen.",
"Ein Vogel hat niemals Angst davor, dass der Ast unter ihm brechen könnte.<br><br>Nicht, weil er dem Ast vertraut, sondern seinen eigenen Flügeln.<br><br>Verliere nie den Glauben an Dich selbst.",
"Du kannst und darfst denken was Du willst. Dein Wille geschehe."
];
