var motivationTextEn = ["Dance, sing, whistle whenever the mood strikes, because the day will come when all you hear is the silence of your grave", "Happiness is all a matter of perspective", "You can either live out your dreams or your fears", "Fear’s in your head<br>But so is courage", "You’re never going to be as young as you are today!", "You’re a winner!", "Believe in yourself<br>", "Today is a gift and the only day which you can change", "Never give up and stick with it until you succeed!", "Be brave and take risks because that’s only way you can achieve greatness", "Humour is the father and laughter the mother of a happy soul", "Be thankful for everything, including your problems, because this is the fertiliser that will help you to grow!", "Love is not just the foundation of all things; it is also the pinnacle of all things", "If you want to experience a miracle in your life, get rid of your fear and doubts", "The direction of your thinking and your action is always forward, into the future. That’s why God gave you eyes that face forward", "A true friend will always carry you from one height to another. You can choose your friends", "Believe in yourself. Believe that the divine energy is in you and on your side at all times", "Always be yourself in the here and now. Compliment yourself and others. Turn yourself and those around you into giants", "The key to happiness lies inside you", "Believing in your purpose with all your heart<br>is the secret of the gods", "You are the most important person in your life, so love yourself and respect yourself", "Happiness doesn’t depend on who you are or what you have. It depends on how you think", "Pain and stress are the first sprouts on the way to success", "You are unique", "If you embody love, then fear itself will be afraid and flee", "Your thoughts are food for your soul.", "You alone are the director of your life", "Clean your life by cleaning up your thoughts", "What’s important is not where you’re at today or where you’ve come from. What’s important is where you’d like to go", "noNever stop smiling<br><img src='img/lachen_musst_selber.jpg' class='img-circle'><br>even when you’re really sad, because you never know who might just fall in love with your smile<br>", "noWhen others think you’re finished<br><img src='img/weiter1.jpg' class='img-circle'><br>is where you’re actually just getting started", "noIf God wants to give you a special gift, he’ll wrap it in a problem<br><img src='img/problem_ist_ein_geschenk.jpg'>", "Believe in yourself. If you don’t, who will?", "noYou’re a diamond<br><img src='img/du_bist_ein_diamant1.jpg' class='img-circle'><br>in the rough and also the sharpening stone", "noMiracles happen <br><img src='img/glueck3.jpg' class='img-circle'>when you purify your mind of all fears and doubts", "Let go and become richer<br>", "noHave the courage to master the challenges in your life<br><img src='img/hindernis.jpg' class='img-circle'>", "The more love for yourself that you show, the more certain people and positive situations you’ll attract", "Set yourself goals, divide them into steps, and then walk the walk, step-by-step", "Whether you win or lose depends on what’s going on between your ears.", "The world belongs to those who want to conquer it with love and good spirits", "Enjoy the moment because the moment is your life", "You don’t need to be better than everyone else. You just need to be better than you ever imagined you could be", "When the future’s facing you, give it the chance to be experienced! When uncertainty’s facing you, give it the chance to become certainty! When reason’s blocking your path, give yourself the opportunity to decide from your gut. When love’s standing there, give it every chance in the world!", "noYou don’t need to do everything right in life. There won’t be any grades on your gravestone<img src='img/lu1.jpg' class='img-circle'>", "noLoving yourself lets the butterflies fly<br><img src='img/du_bist_ein_schmetterling.jpg'>", "Just be yourself", "Every hour, every minute of your life is a gift. Don’t postpone anything that makes you happy. Because you never know how much time you’ll have left...", "We need to understand that earth is a school where we have certain things to learn, for example, patience, perspective, spiritual and creative powers, and especially love, both love for yourself and for others. Love is the most important and best homework you’ll ever get in the school of life", "Do you want to be happy? Then don’t live in the past, don’t live in the future, just live in the moment and appreciate just how unique it is", "noGod gave you a face, but you’ve got to do the laughing yourself<br><img src='img/lachen_musst_selber.jpg' class='img-circle'><br>", "noMiracles begin<br><img src='img/glueck3.jpg' class='img-circle'> when we devote more energy to our dreams than to our fears", "Give every day the chance to be the best day of your life", "The hardest times often lead to the best moments in your life. Keep the faith. Everything will be worth it in the end<br>", "Be brave enough to start. It’s never too late to do what you could have done<br>", "You can’t decide everything that’s going to happen in life, but you can decide how you’re going to handle it. Don’t let your past define your present, instead let it give you advice for the future", "Everything that you are, everything that you want, everything that you should be, comes from inside", "You are unique. Believe in yourself now and for ever.", "Whatever you think, you’ll achieve. Whatever you feel, you’ll attract. Whatever you imagine, you will receive<br>&#x1f496;", "No matter what you do, they’ll think of you the way they want to, so do what you want to do and be the person you really are, because that’s how you’ll feel good with yourself", "Take your life into your own hands, or else others will do it for you", "Everything you need to be successful is already inside you", "Be brave enough to change<br>", "Be grateful for what you have while you work for what you want", "Walk your path and believe in yourself, no matter what others say", "It’s your life. Believe in yourself<br>", "noYour motivation machine<br><img src='img/motivationsmaschine.jpg' class='img-circle'>"];

var motivationTextEs = ["Baila, canta y silba cuando siempre tengas ganas, porque llegará el momento en el que solo escucharas el silencio de tu tumba", "La felicidad se produce con la forma de pensar", "Puedes vivir tus visiones o tus miedos", "El miedo empieza en la cabeza, por supuesto el coraje tambien", "Tan joven como hoy no volveras a serlo en toda tu vida!", "Tu eres un ganador! Creé en tí!", "El hoy es un regalo y el único día en el que puedes cambiar algo", "nunca … nunca … jamas te des por vencido y ten el aguante para tener éxito", "Ten el valor para riesgos, porque solo através de este valor podras obtener la verdadera grandeza", "El humor es el padre , la risa  la madre de personas felices", "Se agradecido por todo, porque eso es el abono para poder crecer", "El amor no es solo el fundamento de todas las cosas, es mucho mas, es también la cima de todas las cosas", "Si quieres atraer un milagro a tu vida, despide el miedo y la duda de tu mente", "Mantén la dirección de tus pensamientos y acciones siempre para adelante en el futuro, pues tu creador te dió los ojos hacia adelante", "Un verdadero amigo te inspira de pico a pico, tu puedes elegir a tus amigos", "Cree en ti, cree en la energia divina que siempre está contingo y siempre está para ti", "Se siempre tu mismo en el ahora y aqui, piropéate  y piropéa a los demas, hazte gigante y haz a los demas gigantes", "La llave para tu felicidad está en ti mismo", "Cree de corazon en tu meta<br>eso es el misterio de dios", "Tú eres la persona más importante en tu vida, por eso ámate y respétate a ti mismo", "La suerte no depende de quien eres o de lo que tienes, solo depende de lo que piensas", "El dolor y el efuerzo son los escalones hacia éxito", "Tú eres único", "Si vives el amor, el miedo tiene miedo y huye", "Tus pensamientos son el alimento de tu alma", "Solo tú eres el director de tu vida", "Purifica tu vida  através de la purificación de tus pensamientos", "No es importante donde estas ahora o de dónde vienes, lo importante es adonde quieres ir", "noNunca dejes de sonreird<br><img src='img/lachen_musst_selber.jpg' class='img-circle'><br>ni siquiera cuando estés muy triste, porque nunca se sabe quién se podría enamorar de tu sonrisa<br>", "noCuando los demas piensen que te vas a dar por vencido<br><img src='img/weiter1.jpg' class='img-circle'><br>entonzes más que nunca sique con lo tuyo", "Cuando Dios te quiere hacer un regalo especial, lo empaqueta en un problema", "Cree en ti, porque si no lo haces tú, quién va creer en ti?", "noTú eres el diamante<br><img src='img/du_bist_ein_diamant1.jpg' class='img-circle'><br>y también la piedra de afilar", "Milagros ocurren si purificas tu mente de todas las angustias y dudas", "Suelta y de este modo enriqueze", "noTen el valor para superar los obstáculos de tú vida<br><img src='img/hindernis.jpg' class='img-circle'>", "Cuanto más amor propio rezumas, más personas y situaciones positivas atraeras", "Ponte metas, repartelas en etapas y anda paso a paso", "Es entre las orejas donde se gana o se pierde", "El mundo es de aquellos quienes salen a conquistar, armados con amor y buen humor", "Disfruta del momento, porque el momento es tu vida", "No tienes que ser mejor que todos los demás, solo tienes que ser mejor de lo que tu jamas hubieras pensado poder ser", "Si el futuro está delante de ti, dale la oportunidad de ser vivido. Si la incertidumbre está delante de ti, dale la oportunidad de convertirse en certeza. Si la razón está delante de ti, dale la oportunidad de que pueda decidir por intuición. Si el amor está delante de ti, dale todas las oportunidades del mundo<br>", "noNo hay que hacer todo bien en la vida, el la lápida no ponen notas<br><img src='img/lu1.jpg' class='img-circle'>", "noTú eres una mariposa, porque el amor propio tambien deja volar mariposas<br><img src='img/du_bist_ein_schmetterling.jpg'>", "noCachondo es …. zılǝɟ ɹǝs ʎ ɐqıɹɹɐ sɐʇɐd opunɯ lǝ opuɐnɔ uǝ zǝʌ ǝp ɹǝuod<br><img src='img/umdrehen.jpg' class='img-circle'>", "Se soló tu mismo", "Cada hora, cada minuto de tú vida es un regalo. No aplazes nada de lo que dé placer, porque nunca se sabe cuanto tiempo te queda …", "Tenemos que entender, que la tierra es una escuela en la cual tenemos que aprender ciertas cosas. Por ejemplo paciencia, tolerancia, el desarollo de capacidades mentales y creativas y sobre todo amor, amor de sí mismo y amor a los demás. Amor es en todas las clases de la escuala de la vida la asignatura principal y por lo tanto la tarea mas bonita e importante", "noQuieres ser feliz?<br><img src='img/glueck3.jpg' class='img-circle'><br>Pues entonces no vivas en el pasado, no vivas en el future, sino vive ahora en este momento y goza de este momento único<br>", "noDios te dió el rostro, pero reir tienes que reirte tu mismo<br><img src='img/lachen_musst_selber.jpg' class='img-circle'>", "noMilagros empiezan a cumplirse cuando damos <br><img src='img/glueck3.jpg' class='img-circle'>más energia a nuestros sueños que a nuetros miedos", "Dale a cada día la oportunidad de ser el más bonito de tú vida", "Los momentos más dificiles conducen a menudo a los momentos más maravillosos de tú vida", "La valentía está al principio. Nunca es tarde para llegar a ser lo que uno hubiera podido ser", "No puedes elegir lo que en la vida va a suceder, pero puedes elegir cómo manejar la situación. No dejes de que el pasado mande en el presente y deja ser al pasado un buen aconsejador del futuro", "Todo lo que eres, todo lo que quieres, todo lo que debes, sale de tí mismo", "Tú eres único. Cree en tí. Ahora y para siempre", "Lo que piensas, vas a crear. Lo que sientes, vas a atraer. Lo que te imaginas, lo vas a recibir<br>&#x1f496;", "Da lo mismo lo que hagas, todo el mundo va a pensar lo que quiera de tí, por eso haz luego lo que de corazón quieras y sé la persona que realmente eres, ya que entonces vas a sentirte bien contigo mismo<br>&#x1f497;", "Toma tú vida en tus propias manos, de lo contrario otros lo harán por tí", "Todo lo que necesitas para tener éxito ya lo tienes dentro de tí", "Se una y otra vez valiente para cambiarte", "Se agradecido de lo que tienes mientras que trabajas por lo que pretendes", "Sigue tú camino y cree en ti mismo, no importa lo que digan los demás", "Es TU vida, cree en ti<br>", "noSu motivación máquina<br><img src='img/motivationsmaschine.jpg' class='img-circle'>"];

var motivationTextTest = [
    "Dein wahrer Reichtum sind Deine Gedanken."
];

var motivationTextPL = [
"To takie cenne i piękne, że istniejesz.",
"Twoim prawdziwym bogactwem są Twoje myśli.",
"Dąż do bycia pierwszym: jako pierwszy skinij głową, uśmiechnij się, pochwal i przebacz.",
"Jesteś sobą, gdy nie kwestionujesz już swoich działań.",
"Nie czekaj, aż ludzie uśmiechną się do Ciebie, pokaż im, jak to się robi!",
"Ucz się na błędach, aż przestaniesz je popełniać.",
"Wdech<br>Wydech<br>Szczęście.",
"Masz zdolność motywowania się do działania. Po prostu to zrób!",
"Każda, nawet najdłuższa podróż, zaczyna się od pierwszego kroku.",
"Złamane serce nie jest tego warte. Kiedy półbogowie odchodzą, przychodzą bogowie.",
"Czy wiesz, że motyl nie może zobaczyć swoich skrzydeł? Nie wie, jak piękne są, ale wszyscy inni to widzą. Podobnie jest z ludźmi.",
"Miej słońce w sercu, bez względu na burze czy śnieg. Słońce rozświetli Ci nawet najciemniejszy dzień.",
"Bez względu na to, co się dzieje, wierz w siebie! Bez względu na wszystko, bądź wierny sobie!",
"Sekretem bogów jest ciągłe wierzenie w siebie.",
"Szczęście tkwi w działaniu.",
"Wytrwałość to ukryta siła sukcesu. Bądź niezłomny.",
"Jestem wdzięczny za kamienie, które stanęły na mojej drodze. Bez nich nie odkryłbym swojej siły.",
"Nigdy nie zadowolisz wszystkich swoimi działaniami. Nawet jeśli będziesz chodzić po wodzie, ktoś powie, że nie umiesz pływać.",
"Nie marnuj energii na negatywy. Skup się na pozytywnym celu i tym, co chcesz osiągnąć.",
"Pokochaj siebie takim, jakim jesteś, a nie takim, jakim chcieliby Cię widzieć inni.",
"Jesteś cudowny.",
"Przeznaczenie to to, co z niego zrobisz.",
"Bądź szczęśliwy tu i teraz.",
"Przestań się porównywać, uśmiechnij się do lustra.",
"Pamiętaj o swoich marzeniach, one za Tobą tęsknią.",
"Jeśli dmuchawiec potrafi przebić się przez asfalt, Ty również znajdziesz swoją drogę!",
"Postanowiłem nie czekać na lepsze czasy. Najlepszy czas jest teraz.",
"Bez względu na sytuację, w jakiej się znajdujesz, wierz w najważniejszą osobę – siebie!",
"Ciesz się życiem. Utracony czas nigdy nie wróci. Żyj swoimi marzeniami i nie poddawaj się w ich realizacji.",
"Życie to przygoda: żyj, czuj, kochaj, śmiej się, płacz, graj, wygrywaj, przegrywaj, potykaj się… ale zawsze wstań i idź swoją drogą.",
"Nigdy nie wstydź się podejmować działań, które mogą zmienić Twoje życie. To może być Twoje szczęście.",
"Tańcz, śpiewaj i gwizdaj, kiedy tylko masz na to ochotę, bo kiedyś usłyszysz tylko ciszę swojego grobu.",
"Bądź zawsze wierny sobie, ze wszystkimi swoimi pragnieniami i marzeniami. Nie udawaj i idź swoją drogą. Przebacz sobie swoje słabości z miłością i bądź dzięki temu silny.",
"Ten moment jest wyjątkowy i nigdy nie wróci. Nie czekaj na idealny moment. Spraw, by był idealny dla Ciebie.",
"Dziś jest pierwszy dzień reszty Twojego życia.",
"Z miłością przebaczam sobie swoje słabości i dzięki temu jestem silny.",
"Rozpoznaj, że dzisiejszy dzień to Twoja szansa.",
"Zawsze jesteś swoim własnym nauczycielem.",
"Perfekcja jest nudna i powstrzymuje Cię przed ukończeniem swoich działań.",
"Nie ma nic większego niż wiara w siebie!",
"Szczęście wynika z Twojego sposobu myślenia.",
"Bóg słucha myśli.",
"Możesz żyć swoimi wizjami lub swoimi lękami.",
"Strach rodzi się w głowie. Odwaga również.",
"Jesteś zwycięzcą!",
"Uwierz w siebie!",
"Dziś jest prezent i jedyny dzień, w którym możesz coś zmienić.",
"Nigdy się nie poddawaj. Miej wytrwałość, by osiągnąć sukces!",
"Miej odwagę podejmować ryzyko, bo tylko dzięki temu możesz zyskać prawdziwą wielkość.",
"Humor jest ojcem, a śmiech matką szczęśliwego człowieka.",
"Bądź wdzięczny za wszystko, nawet za swoje problemy. To nawóz dla Twojego wzrostu.",
"Miłość jest nie tylko fundamentem wszystkiego, jest również szczytem wszystkiego.",
"Chcesz przyciągnąć cud do swojego życia? Uwolnij swoje myśli od strachu i zwątpienia.",
"Kierunek Twojego myślenia i działania zawsze prowadź naprzód w przyszłość.",
"Prawdziwy przyjaciel zawsze motywuje Cię, byś wspinał się od jednego szczytu do drugiego. Możesz sam wybrać swoich przyjaciół.",
"Wierz w siebie i w boską energię, która zawsze jest w Tobie i dla Ciebie.",
"Zawsze bądź sobą w tu i teraz.",
"Klucz do Twojego szczęścia znajduje się w Tobie.",
"Wiara w swoje cele to sekret bogów.",
"Jesteś najważniejszą osobą w swoim życiu, więc kochaj i szanuj siebie.",
"Szczęście nie zależy od tego, kim jesteś, czy co masz, ale od tego, co myślisz.",
"Ból i wysiłek to szczeble drabiny prowadzącej do sukcesu.",
"Jesteś wyjątkowy."
];



    
var motivationText = [
"Es ist so wertvoll und schön dass es Dich gibt",    
"Dein wahrer Reichtum sind Deine Gedanken.",
"<img src='img/erster.png'>Strebe danach, Erster zu sein: Als Erster zu nicken, als Erster zu lächeln, als Erster ein Kompliment zu machen und als Erster zu vergeben.","Du bist Du selbst, wenn Du Deine Handlungen nicht mehr HINTERFRAGST","Warte nicht darauf dass die Menschen Dich anlächeln, <img src='img/zeigeesihnen.jpg'>zeige es Ihnen wie es geht!","Aus Fehlern solange zu lernen, bis Du sie nicht mehr machst.<img src='img/lernen.jpg' class='img-circle'>","Einatmen<br>Ausatmen<br>Glücklichsein<img src='img/gluecklich1.jpg' class='img-circle'>","noDu hast die Fähigkeit Dich zum Handeln zu motivieren.<br><img src='img/doit.png' class='img-circle'> Tue es einfach!","Jede, auch noch so lange Reise, beginnt mit dem ersten Schritt<img src='img/doit.png' class='img-circle'>","Liebeskummer lohnt sich nicht. <img src='img/neuanfang.jpg'> Wenn Die Halbgötter gehen kommen die Götter","no<img src='img/butterfly.jpg' class='img-circle'>Wusstest Du, dass es für einen Schmetterling unmöglich ist, seine eigenen Flügel zu sehen?<br> Wusstest Du auch, dass seine Flügel als eine der schönsten Errungenschaften in der Natur gelten?<br>Er kann nicht sehen wie schön sie sind, aber alle anderen können es.<br>Genauso ist es bei uns Menschen<img src='img/butterfly1.jpg'>",
"no<img src='img/sun1.jpg' class='img-circle'>Hab Sonne im Herzen, egal ob es stürmt oder schneit, ob der Himmel voll Wolken, die Erde voll Streit - hab Sonne im Herzen, dann komme was mag, das leuchtet voll Licht dir den dunkelsten Tag<img src='img/sun.jpg' class='img-circle'>",
"Egal was passiert.Glaube an Dich!<br>Egal was passiert.Bleib Dir treu!<br>Egal was passiert.Habe Dich lieb!<br>","Und immer wieder an Dich selber zu glauben ist das Geheimnis der Götter.","Glück liegt auch im Handeln und Tun.","Beharrlichkeit ist die geheime Stärke des Erfolgreichen. Sei unerschütterlich.","noIch bin dankbar für die Steine die mir in den Weg gelegt wurden.<img src='img/steine.jpg' class='img-circle'>Ohne Sie wäre ich sonst nicht über meine Stärken gestolpert.","<b>Du kannst nie alle mit Deinem Tun begeistern.</b><br>Selbst wenn Du übers Wasser laufen kannst, kommt einer daher und fragt ob Du zu blöd zum Schwimmen bist.","noVerwende nicht so viel Energie auf das Negative.<img src='img/bogen1.jpg' class='img-circle'>Fokussiere dich auf Dein positives Ziel und das, was du erreichen willst.<img src='img/bogen2.jpg' class='img-circle'>","Fange an Dich zu lieben wie Du bist und nicht wie Dich Andere gern sehen würden.","Du bist WUNDERBAR","Schicksal ist immer was du daraus machst","Sei einfach glücklich im Jetzt<img src='img/t161.jpg' class='img-circle'>","Hör auf Dich zu vergleichen, lächle in den Spiegel","Denke an Deine Träume, sie vermissen Dich.","Sei einfach glücklich im Jetzt","no<img src='img/loewenzahn.jpg' class='img-circle'><br>Wenn es ein Löwenzahn durch den Asphalt schafft, dann wirst Du doch sicher auch einen Weg finden!",
"noIch habe entschieden nicht länger auf bessere Zeiten zu warten.<br>Die besten Zeiten sind jetzt.<br>Ich mache die restlichen Jahre meines Lebens zu den glücklichsten.<img src='img/jetzt.jpg' class='img-circle'><br>Denn das Leben gehört mir und es ist einfach zu kurz um noch länger zu warten.",
"Egal in was für einer Lebenslage Du dich gerade befindest. Glaube an den wichtigsten Menschen = DICH",
"Genieße Dein Leben. Verlorene Zeit kehrt niemals zurück. Lebe in Deinem Traum und gebe niemals auf ihn zu verwirklichen","Das Leben ist wie ein Abenteuer, lebe, fühle, liebe, lache, weine, spiele, gewinne, verliere, stolpere...doch erhebe Dich immer wieder und gehe Deinen Weg",
"Sei dir nie zu schade etwas zu unternehmen was dein leben verändern würde.<br>Es könnte dein Glück sein.",
"Tanze singe und pfeife wann immer Du Lust danach hast<br>denn irgendwann hörst Du nur noch die Stille von Deinem Grab",
"Bleib Dir immer selbst treu, mit all Deinen Wünschen und Träumen. Verstell Dich nicht und geh Deinen Weg. Vergebe Dir Deine Schwäche mit Liebe und sei dadurch stark.",
"Dieser Moment ist einzigartig und kommt nie wieder zurück. Warte nicht auf den perfekten Moment. Mache ihn dir perfekt.",
"Heute ist der erste Tag vom Rest Deines Lebens.",
"In Liebe vergebe ich mir meine Schwäche und bin dadurch stark",
"Erkenne daß im heutigen Tag Deine Chance liegt",
"Du bist immer selbst dein Lehrer",
"Perfektion ist kotzlangweilig und hält dich davon ab mit deiner Sache fertig zu werden",
"Es gibt nichts größeres als an Dich zu glauben!",
"Glück entsteht durch deine Art zu Denken",
"Gott hört auf die Gedanken",
"Du kannst entweder deine VISIONEN oder deine Ängste leben",
"Die Angst hat ihren Anfang im Kopf<br>Der Mut allerdings auch", "noDeine Motivations Maschine<img src='img/motivationsmaschine.jpg' class='img-circle'>",
"So jung wie heute wirst Du nie wieder<br>in Deinem Leben!",
"Du bist ein Gewinner!", "Glaube an Dich",
"Heute ist ein Geschenk<br> und der einzigste Tag<br>an dem Du etwas verändern kannst",
"Gebe nie<br>nie<br>niemals auf<br><br>und habe die Ausdauer zum Erfolg!",
"Habe den Mut zu Risiken<br>denn nur durch diesen Mut<br>kannst Du an wahrer Größe gewinnen",
"Der Humor ist der Vater &#9786;<br>das Lachen die Mutter<br>eines glücksgemütlichen Menschen<br><img src='img/humor.jpg' class='img-circle'>",
"Sei bei allem dankbar<br>Auch für Dein Problem<br>denn dies ist der Dünger<br>für Dein Wachstum!",
"Die Liebe ist nicht nur das Fundament aller Dinge <br>&#9825;sie ist viel mehr<br>&#9825;<br>sie ist auch der Gipfel aller Dinge",
"Willst Du ein Wunder in Dein Leben ziehen<br><br>so entlasse die Angst und den Zweifel<br>aus Deinen Gedanken",
"Die Richtung Deines Denkens und Tuns<br>halte stets nach vorne in die Zukunft<br><br>denn Dein Schöpfer gab Dir die Augen vorne",
"Ein wahrer Freund beflügelt Dich immer<br>von einem Gipfel zum anderen zu kommen.<br>Du kannst Dir Deine Freunde aussuchen",
"Glaube an Dich<br><br>Glaube daran dass die göttliche Energie immer in Dir<br>und für Dich ist<br>",
"Sei immer Du selbst<br>im Jetzt und Hier<br>mache Dir und anderen Komplimente<br>mache Dich und andere zu Riesen",
"Der Schlüssel &#9825;<br>zu Deinem Glück<br>liegt in Dir",
"Mit dem Herzen an Dein Ziel glauben<br> das ist das Geheimnis der Götter",
"Du bist der wichtigste Mensch in Deinem Leben<br>deshalb habe Dich lieb &#9825;<br>und respektiere Dich", "no<img src='img/glueck3.jpg' class='img-circle'><br>Glück hängt nicht davon ab<br>wer Du bist oder was Du hast<br>es hängt nur davon ab<br>was Du denkst",
"Schmerz und Anstrengung<br>sind die Leitersprossen<br>zum Erfolg",
"Du bist<br>&#9825;<br>einzigartig", "Wenn Du die Liebe lebst<br>&#x1f496;<br>dann hat die Angst angst und sie flüchtet",
"Deine Gedanken<br>sind die Nahrung<br>für Deine Seele<br>",
"Du allein<br>bist der Dirigent<br>Deines Lebens&nbsp;&#9835;",
"Reinige Dein Leben<br>durch die Reinigung<br>Deiner Gedanken",
"Wichtig ist nicht wo Du jetzt stehst oder woher Du kommst<br>entscheidend ist wohin Du willst",
"noHöre nie auf zu lächeln<br><img src='img/lachen_musst_selber.jpg' class='img-circle'><br>auch dann nicht wenn Du sehr traurig bist<br>denn Du weisst nicht wer sich vielleicht in Dein Lächeln verliebt<br>",
"noWenn andere denken Du bist am Ende<br><img src='img/weiter1.jpg' class='img-circle'><br>so fange erst richtig an",
"noWenn Gott Dir ein besonderes Geschenk machen will<br>verpackt er es in ein Problem<br><img src='img/problem_ist_ein_geschenk.jpg'>",
"Glaube an Dich<br>denn wenn Du es nicht tust<br>wer soll dann an Dich glauben?<br>",
"noDu bist ein Diamant<br><img src='img/du_bist_ein_diamant1.jpg' class='img-circle'><br>und der Schleifstein dazu",
"Wunder geschehen<br><br>wenn Du Deine Gedanken<br>von allen Ängsten und Zweifeln<br>reinigst",
"Lasse los<br>und werde dadurch<br>reicher",
"noHabe den Mut<br>die Hürden Deines Lebens<br>zu meistern<br><img src='img/hindernis.jpg' class='img-circle'>",
"Je mehr Selbstliebe du ausstrahlst<br>umso mehr wohl gestimmte Menschen und positive Situationen<br>ziehst Du an<br>",
"Setze Dir Ziele<br>teile sie in Etappen ein<br>und gehe Schritt für Schritt ",
"Zwischen den Ohren  wird gewonnen oder verloren",
"Die Welt gehört denen, die zu Ihrer Eroberung ausziehen<br>bewaffnet mit Liebe und guter Laune",
"Genieße den Augenblick<br>denn der Augenblick<br>ist Dein Leben  ",
"Du musst nicht besser sein als jeder andere <br>Du musst nur besser sein als Du jemals gemeint hast sein zu können",
"Wenn die Zukunft vor Dir steht<br>gib ihr die Chance erlebt zu werden<br><br>Wenn die Ungewissheit vor Dir steht<br>gib ihr die Chance Gewissheit zu werden<br><br>Wenn die Vernunft vor Dir steht<br>gib ihr die Chance aus dem Bauch zu entscheiden<br><br>Wenn die Liebe vor Dir steht<br>dann gib ihr jede Chance der Welt<br>&#9825;",
"noMan muss im Leben nicht alles richtig machen...<br>auf dem Grabstein<br>stehen keine Noten<img src='img/lu1.jpg' class='img-circle'>",
"noDenn sich selbst zu lieben<br>lässt auch Schmetterlinge fliegen<br><img src='img/du_bist_ein_schmetterling.jpg'>",
"noGeil ist...<br>uıǝs nz ɥɔılʞɔülƃ ıǝqɐp pun uǝllǝʇs nz ɟdoʞ uǝp ɟnɐ ʇlǝʍ ǝıp nz pun qɐ<br><img src='img/umdrehen.jpg' class='img-circle'>", "Sei einfach<br>Du<br>selbst<br>",
"Jede Stunde<br>jede Minute in Deinem Leben ist ein Geschenk<br>Verschiebe nichts<br>was Deinem Leben Freude bereitet<br>Denn Du weißt nicht<br>&#8987;<br>wieviel Zeit Dir noch bleibt...",
"Wir müssen verstehen<br><br>dass die Erde eine Schule ist<br>in der wir bestimmte Dinge zu lernen haben<br> beispielsweise Geduld<br>Nachsicht<br>die Entwicklung geistiger und schöpferische Fähigkeiten und vor allem Liebe<br>und das heisst <b>Liebe zu sich selbst</b> und zu anderen<br>Liebe ist in allen Klassen der Lebensschule das Hauptfach<br>also somit die wichtigste und schönste Lernaufgabe<br>&#9825;",
"noWillst Du glücklich sein?<br><img src='img/glueck3.jpg' class='img-circle'><br>Dann lebe nicht in der Vergangenheit<br>Lebe nicht in der Zukunft<br>sondern lebe jetzt<br>in diesem Augenblick<br>und genieße diesen einzigartigen Moment<br>",
"noGott hat Dir ein Gesicht gegeben<br>doch Lachen musst Du selber<br><img src='img/lachen_musst_selber.jpg' class='img-circle'>",
"noWunder beginnen dann<br>wenn wir unseren Träumen<br><img src='img/glueck3.jpg' class='img-circle'>mehr Energie geben<br>als unseren Ängsten",
"Gib jedem Tag die Chance der Schönste in Deinem Leben zu werden",
"Die härtesten Zeiten leiten Dich oft zu den grossartigsten Momenten Deines Lebens. Bewahre den Glauben. Alles wird es wert sein am Ende", "Mut steht am Anfang!<br> Es ist nie zu spät das zu werden was man hätte sein können.",
"Du kannst Dir nicht aussuchen was im Leben alles passiert aber Du kannst Dir aussuchen wie Du damit umgehst. Lass Dir Deine Gegenwart nicht von Deiner Vergangenheit bestimmen und lass die Vergangenheit ein guter Ratgeber für die Zukunft sein",
"Alles was Du bist<br>alles was Du willst<br>alles was Du sollst<br>geht von Dir selbst aus",
"Du bist einzigartig<br>Glaube an Dich<br>Jetzt und für immer", 
"Was Du denkst erschaffst Du<br>Was Du fühlst ziehst Du an<br>Was Du Dir vorstellst wirst Du bekommen", 
"Egal was Du tust jeder denkt sowieso von Dir was er will, deshalb kannst Du gleich tun was Du von Herzen willst und der sein, der Du wirklich bist, denn dann fühlst Du Dich mit Dir selbst wohl",
 "Nimm Dein Leben selbst in die Hand<br>Sonst werden es andere für Dich tun<br>", 
 "Alles was Du brauchst um erfolgreich zu sein hast Du bereits in Dir", 
 "Sei immer wieder mutig Dich zu verändern", 
 "Sei dankbar für das was du hast<br> während du für das arbeitest<br>was du willst", 
 "Geh deinen Weg und glaub an dich<br>egal was andere sagen", 
 "Es ist Dein Leben<br>Glaube an Dich",
 "Der jetzige Augenblick ist Deine Zukunft",
 "Höre nie auf zu lächeln. Es ist besser mit Falten im Gesicht alt zu werden, als mit Falten auf dem Herzen",
 "Du bist wundervoll! VERGISS DAS NIE",
 "Wenn Du dich umschaust und alles ist dunkel, schau noch einmal, vielleicht bist Du das Licht",
 "Hab nie Angst vor dem Altwerden. Du kannst immer noch viel Unsinn machen. Nur langsamer.",
 "Pflege Deine Gedanken. Was wir denken, wird in uns wachsen",
 "Sei der Grund, warum andere Menschen wieder an das Gute im Menschen glauben",
 "Wünsche muss man loslassen, damit sie gehen können. Nämlich in ERFÜLLUNG...",
 "Man muß nicht viel besitzen um viel geben zu können! Die Geste die vom Herzen kommt - die macht's aus!",
 "Man muß mit allem rechnen. Auch mit dem Guten",
 "Glaube an Dich und zweifle nicht an dem was Du tust, sondern denke darüber nach was Du wirklich willst. Ohne Angst vor dem, was daraus werden könnte. Denn was vor uns liegt und was hinter uns liegt, ist nichts im Vergleich zu dem, was in uns liegt. Und wenn wir das was in uns liegt nach außen in die Welt tragen, geschehen Wunder",
 "Sei frech und wild und wunderbar",
 "Wer Freude schenkt bringt Licht in einsame Herzen",
 "Eines Tages klopfte die Angst an die Tür. Der Mut stand auf und öffnete, aber da war niemand draußen.",
 "Wer gelernt hat im Dunkeln zu laufen, der braucht auch keine Blender um sich.",
 "Glaube an Dich! Du hast in deinem Leben schon so vieles GEMEISTERT. DU WIRST ES AUCH DIESMAL SCHAFFEN!",
 "Die Welt gehört denen, die sich trauen anders zu denken",
 "Du wirst leiden, solange Du eine emotionale Reaktion auf alles hast was zu Dir gesagt wird.<br>Wahre Kraft liegt darin, Dich zurück zu lehnen und die Dinge mit Logik & Ruhe zu betrachten.<br><br>Wenn Worte Dich kontrollieren können, bedeutet das, dass jeder Dich kontrollieren kann.<br>Atme durch und erlaube manches einfach los zu lassen.<br><br>Bruce Lee",
 "Die Zukunft hängt davon ab, was Du heute tust.<br> ",
 "Träume können die Zukunft verändern. Doch erst wenn man die Augen öffnet, kann man sie verwirklichen",
 "Schwierige Straßen führen oft zu wunderschönen Zielen",
 "Jeder muss an etwas glauben. Warum dann nicht an sich selbst?",
 "Hör nie auf zu lächeln. Es ist besser, mit Falten im Gesicht alt zu werden, als mit Falten auf dem Herzen.",
 "Wenn Du weisst wie mächtig Deine Gedanken sind, wirst Du nie wieder negativ denken!",
 "Woher wusstest Du, dass Du es schaffst? <br><br><br>Ich wusste es nicht.<br>Ich wollte es!!!",
 "Lass das Leben doch einfach mal machen und vertraue ihm",
 "noDie besten Menschen sind die, mit Flausen im Kopf, <img src='img/t194.jpg' class='img-circle'>dem Arsch in der Hose und dem Herz am rechten Fleck",
 "Um Deine Ängste zu überwinden musst Du Durch Sie hindurch und nicht um sie herum.",
 "Wer nicht den Mut hat, Ängste zu durchleben, kann nicht wachsen.",
 "Sei realistisch, plane ein Wunder",
 "Glück ist, wenn Du mit Dir selbst zufrieden bist<br> und dafür nicht die Bestätigung anderer brauchst.",
 "Du bist nicht schuld für die Programmierung, welche Du als Kind erfahren hast.<br><br>Als Erwachsener liegt es jedoch in DEINER vollen Verantwortung, um es wieder in Ordnung zu bringen.",
 "noDie besten Menschen sind die, mit Flausen im Kopf, <img src='img/t194.jpg' class='img-circle'>dem Arsch in der Hose und dem Herz am rechten Fleck",
 "Bleibe im Vertrauen zu Dir selbst und in Deiner goldenen Mitte",
 "Finde den <b>Mut</b> für die Veränderung, die Du Dir wünschst,<br><br>die <b>Kraft</b> es durchzuziehen<br><br>und den <b>Glauben</b> daran, dass sich alles zum Besten wenden wird.",
 "Du kannst nicht zurück gehen und den Anfang ändern.<br><br>Aber Du kannst jetzt neu Anfangen und das Ende ändern!",
 "Wunderschöne Dinge werden passieren, sobald Du Dich von dem Negativem Distanzierst!",
 "Wie wird man ein Schmetterling?<br><br>...fragte die Raupe nachdenklich.<br><br>DU MUSST SO SEHR WOLLEN, DASS DU BEREIT BIST, DEINE EXISTENZ ALS RAUPE AUFGEBEN ZU WOLLEN.",
 "Und es kam der Tag, an dem das Risiko, in der Knospe zu verharren, schmerzlicher wurde als zu erblühen!",
 "Du brauchst keinen Lehrer, der Dich beeinflusst.<br><br><br>Du brauchst einen Lehrer, der Dich lehrt, Dich nicht mehr beeinflussen zu lassen.",
 "Ehre Deine Schwächen und Narben mit dem Gold Deiner Selbstliebe",
 "Die Liebe Gottes ist ausgegossen in Dein Herz",
"Glaube an Wunder, Liebe & Glück<br>Schaue nach vorne<br><br>Tue, was Du willst und stehe dazu, denn dieses Leben lebst nur Du!",
"Gib Deiner Vergangenheit nicht die Macht, Deine Zukunft zu beeinflussen!<br><br>Lass sie los, Deine Vergangenheit hat Dir nichts Neues zu sagen.",
"Dein wahrer Reichtum sind Deine Gedanken!",
"Du kannst ein guter Mensch mit einem liebevollen Herz sein und trotzdem 'nein' sagen.",
"Ein Vogel hat niemals Angst davor, dass der Ast unter ihm brechen könnte.<br><br>Nicht, weil er dem Ast vertraut, sondern seinen eigenen Flügeln.<br><br>Verliere nie den Glauben an Dich selbst.",
"Du kannst und darfst denken was Du willst. Dein Wille geschehe."
];
